### ISSUE TITLE
Bump junit to 5.6.2 to better support TempDir on Windows

### ISSUE THREAD

**Issue by victornoel** [artipie/rpm-adapter#101]
Many of our test fails on Windows, and in some case, it is caused by `TempDir` not succeeding in deleting a temporary directory used for test.

In particular I've seen https://github.com/junit-team/junit5/issues/2046, in:
- #95 #96 even though there are other problems related to #86 happening there too...
- #100 where it happens directly without reason 

Latest version of junit should include the fix.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#101](https://github.com/artipie/rpm-adapter/issues/101) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f83958c7-f499-4dcc-a294-06d357d125b8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 should not be update junit version in parent pom instead of updating it only in this project?

**Comment by g4s8** [comment]
> @g4s8 should not be update junit version in parent pom instead of updating it only in this project?

@olenagerasimova correct, I updated junit in parent pom and released `0.3.1`

**Comment by olenagerasimova** [comment]
@g4s8 thanks, I've updated parent pom version in PR #108

**Comment by olenagerasimova** [comment]
@victornoel we've updated junit. Could you please close this issue?

**Comment by victornoel** [comment]
@olenagerasimova thx!

**Comment by 0crat** [comment]
Job was finished in 28 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
