### ISSUE TITLE
XmlFile.java:52-60: Introduce a new class named...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#104]
The puzzle `81-27d531fb` from #81 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/0ba3ae1b9ccca2f5985e4c939b06237d00c2dc7f/src/main/java/com/artipie/rpm/meta/XmlFile.java#L52-L60

The puzzle was created by Victor Noël on 13-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#104](https://github.com/artipie/rpm-adapter/issues/104) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fbdc3f2b-9fb6-46b5-9923-6104b72335d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@g4s8 can I get an example of the result file or information about its structure?

**Comment by g4s8** [comment]
@ammaratef45 there are few example files in test resources: `others.xml.example`, `primary.xml.example`, `filelists.xml.example`

**Comment by ammaratef45** [comment]
@g4s8 classes like `XmlFilelists` and `XmlOthers` have their own inner classes called package and due to this refactoring, `startPackage` can't return a Package and stay universal among them.
should I add a puzzle to refactor this to a universal class instead of inner classes?

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
> @g4s8 classes like `XmlFilelists` and `XmlOthers` have their own inner classes called package and due to this refactoring, `startPackage` can't return a Package and stay universal among them.
> should I add a puzzle to refactor this to a universal class instead of inner classes?

@ammaratef45 I don't think it's a good idea. These inner classes have to be different since they produce different file specific data. If I understood correctly this puzzle #104, it's about creating common behavior to generate the start of XML document, count the number of packages (all 3 metadata files counts packages), and update this counter XML attribute on end. @victornoel please fix me if I'm wrong

**Comment by victornoel** [comment]
@g4s8 @ammaratef45 yes, that was the idea.

I was thinking that `XmlFilelists`, `XmlPrimary` and `XmlOthers` would continue to expose the same behaviour as before without changes to their contract. Instead, their implementations would rely on `XmlPackagesFile`for the common behaviour, including opening and closing the xml for each packages as well as counting them.

If it's not doable in practice for any reason, I think you can find another good way of factoring the common code: the intention behind this design is factorisation.

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/104#issuecomment-616614070))

@ammaratef45 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [6b132591-9d8a-4c0d-9403-84645adeaf41](https://www.0crat.com/footprint/CT2E6TK9B/6b132591-9d8a-4c0d-9403-84645adeaf41), Type: "Cancel order"

**Comment by ammaratef45** [comment]
@g4s8 the reason I gave up on the task is that I was working on it doing something different than what's needed

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/104#issuecomment-616616470))

@ammaratef45 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@7d3334767964, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [1c9ee4c5-f6d0-4a02-bc5a-d3b1fcfa9846](https://www.0crat.com/footprint/CT2E6TK9B/1c9ee4c5-f6d0-4a02-bc5a-d3b1fcfa9846), Type: "Check job status"

**Comment by 0crat** [comment]
The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#104](https://github.com/artipie/rpm-adapter/issues/104), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#104](https://github.com/artipie/rpm-adapter/issues/104) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e6f724c6-a9a2-4aee-b6d8-3bdd339bfc0b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `81-27d531fb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#147](https://github.com/artipie/rpm-adapter/issues/147) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#147](https://github.com/artipie/rpm-adapter/issues/147) is solved here.
