### ISSUE TITLE
XmlRepomd.java:43-51: Refactor this class so it uses...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#105]
The puzzle `81-6d01bf6b` from #81 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/0ba3ae1b9ccca2f5985e4c939b06237d00c2dc7f/src/main/java/com/artipie/rpm/meta/XmlRepomd.java#L43-L51

The puzzle was created by Victor Noël on 11-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#105](https://github.com/artipie/rpm-adapter/issues/105) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1250ecd3-9e30-493e-b061-3c0d6cb222fd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 this is not easy at all... do you know if you will tackle #99 soon?

I think waiting for the choices you will make there is going to be safer before tackling this one...

**Comment by g4s8** [comment]
@victornoel ok, let's wait for #99

**Comment by victornoel** [comment]
@0crat wait for #99 to be done first

**Comment by victornoel** [comment]
@g4s8 is this issue and #99 still in scope nowadays?

**Comment by victornoel** [comment]
@g4s8 ping :)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/105#issuecomment-627819983))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#105](https://github.com/artipie/rpm-adapter/issues/105), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#105](https://github.com/artipie/rpm-adapter/issues/105) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ed736cc7-0813-4be1-abe7-042dd02fe2ad); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 Let's wait for #99, you can assign it to me if you want

**Comment by paulodamaso** [comment]
@0crat wait for #99

**Comment by 0pdd** [comment]
The puzzle `81-6d01bf6b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#105` is not assigned, can't get performer
