### ISSUE TITLE
MetadataFileTest.java:43-47: This test has everything...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#106]
The puzzle `78-ae125758` from #78 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/4ba66c2597bebf9ca6d84e7a7b3b74db9d1c1e47/src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java#L43-L47

The puzzle was created by Victor Noël on 11-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#106](https://github.com/artipie/rpm-adapter/issues/106) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8ced038f-d3e7-4b32-8e29-fc34b3b760ca); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #175

**Comment by 0pdd** [comment]
The puzzle `78-ae125758` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#206](https://github.com/artipie/rpm-adapter/issues/206) is still not solved.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/106#issuecomment-635070222))

@paulodamaso This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#106](https://github.com/artipie/rpm-adapter/issues/106) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23106%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@g4s8 did not got paid, please take a look

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#206](https://github.com/artipie/rpm-adapter/issues/206) is solved here.

**Comment by g4s8** [comment]
@0crat pay 30min @paulodamaso
