### ISSUE TITLE
Meaningful error on broken package

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#110]
Verify that `Rpm.batchUpdate()` throws meaningful error if any of `.rpm` package is broken (not readable). The broken package for test can be created by writing arbitrary data into a file (e.g. `0x00,0x01,0x02`). If exception message will not be clear, then re-throw this exception with understandable message, like `RPM package "package.rpm" is broken, can't be read`.

**Comment by 0crat** [comment]
The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/071200cf-0ce8-4d4b-a90d-32f64337ed9b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-619031919))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#110](https://github.com/artipie/rpm-adapter/issues/110), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-619031919))

@HDouss Job refused in 3 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b1016653-d155-4a4a-96ae-5723114a7f06); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-619237195))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#110](https://github.com/artipie/rpm-adapter/issues/110), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-619237195))

@ammaratef45 Job refused in 4 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e3521e8e-cd59-48d0-9746-aa9c1cf968d5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-619747597))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#110](https://github.com/artipie/rpm-adapter/issues/110), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a7799f06-679e-472a-a555-f96db73542ba); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@g4s8 I think that this one is closely related to https://github.com/artipie/rpm-adapter/issues/63 , so I prefer to do it after we get a resolution there

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/artipie/rpm-adapter/issues/63 resolution

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-635068561))

@paulodamaso This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#110](https://github.com/artipie/rpm-adapter/issues/110) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23110%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@g4s8 something bad happened here, please take a look

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-635167275))

@g4s8 The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/01e780d7-3e41-4836-a954-545792554032); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 I'm afraid that we implemented skipping invalid packages on update instead of failing the update in #223. Could you please tell what was the desired behavior?

**Comment by olenagerasimova** [comment]
@g4s8 agree, thanks

**Comment by 0crat** [comment]
The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#110](https://github.com/artipie/rpm-adapter/issues/110), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/18d6b3ad-5e25-4454-9fbf-3b4a21007f9d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 could you please reassign it to me? #210 was reviewed twice, we had a lot of waiting time, and the PR is good to merge

**Comment by olenagerasimova** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/rpm-adapter/issues/110#issuecomment-644187543))

@olenagerasimova The job [#110](https://github.com/artipie/rpm-adapter/issues/110) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0d7f459a-f8ce-4200-b4ba-1ee668b8cd7a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@olenagerasimova Thanks

**Comment by paulodamaso** [comment]
@0crat wait for #210

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#268](https://github.com/artipie/rpm-adapter/issues/268) is still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 please close, #210 was merged

**Comment by g4s8** [comment]
@olenagerasimova thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cc4a991f-2993-4061-849c-be39b0f7623a, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#110] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [bc3518a8-0bf4-443a-a06f-ccc49a5d768f](https://www.0crat.com/footprint/CT2E6TK9B/bc3518a8-0bf4-443a-a06f-ccc49a5d768f), Type: "Order was finished"

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
