### ISSUE TITLE
Cli.java:41-43: Cli options are not parsed correctly....

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#113]
The puzzle `89-bf69222b` from #89 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/e4f69bb51920538f71e265de91566883b675d2eb/src/main/java/com/artipie/rpm/Cli.java#L41-L43

The puzzle was created by @g4s8 on 09-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#113](https://github.com/artipie/rpm-adapter/issues/113) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2a030c6f-aa67-49a6-bf93-227a31953400); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso FYI see https://github.com/artipie/rpm-adapter/pull/172#discussion_r422328817 that is related to the current todo

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/artipie/rpm-adapter/pull/198 merge

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/artipie/rpm-adapter/pull/198 merge ([here](https://github.com/artipie/rpm-adapter/issues/113#issuecomment-633303149))

@paulodamaso Job [#113](https://github.com/artipie/rpm-adapter/issues/113) is already on hold

**Comment by 0pdd** [comment]
The puzzle `89-bf69222b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#205](https://github.com/artipie/rpm-adapter/issues/205) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#113` is not assigned, can't get performer

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/113#issuecomment-635073911))

@paulodamaso This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#113](https://github.com/artipie/rpm-adapter/issues/113) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23113%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#205](https://github.com/artipie/rpm-adapter/issues/205) is solved here.

**Comment by paulodamaso** [comment]
@g4s8 PLease take a look, I didn't got paid for this one
