### ISSUE TITLE
Cli.java:65-67: Refactor options parsing. Extract the...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#114]
The puzzle `89-d55308e3` from #89 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/e4f69bb51920538f71e265de91566883b675d2eb/src/main/java/com/artipie/rpm/Cli.java#L65-L67

The puzzle was created by @g4s8 on 13-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#114](https://github.com/artipie/rpm-adapter/issues/114) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b34723fb-6a89-44f3-a203-03a0556ffbc5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #172 to be merged

**Comment by victornoel** [comment]
@g4s8 is 0pdd broken? It didn't close the issue

**Comment by 0pdd** [comment]
The puzzle `89-d55308e3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#176](https://github.com/artipie/rpm-adapter/issues/176) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#176](https://github.com/artipie/rpm-adapter/issues/176) is solved here.
