### ISSUE TITLE
XmlPrimaryTest.java:38-42: This test only creates a...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#117]
The puzzle `83-a430163f` from #83 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/e6cf7df9d5ef191d731aa21afd79ef6bb514e484/src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java#L38-L42

The puzzle was created by Victor Noël on 11-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#117](https://github.com/artipie/rpm-adapter/issues/117) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/23cfde48-faab-463a-a285-982ecc65ede9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/117#issuecomment-619031477))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#117](https://github.com/artipie/rpm-adapter/issues/117), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/117#issuecomment-619031477))

@HDouss Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#117](https://github.com/artipie/rpm-adapter/issues/117) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1c7be8c2-b091-40c7-99f5-2c80a7ad88ad); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat wait for merging #156

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/117#issuecomment-630902977))

@g4s8 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#117](https://github.com/artipie/rpm-adapter/issues/117), please stop working. Reason for job resignation: Order was cancelled

**Comment by paulodamaso** [comment]
@0crat wait for #202

**Comment by 0crat** [comment]
> @0crat wait for #202  ([here](https://github.com/artipie/rpm-adapter/issues/117#issuecomment-635075464))

@paulodamaso Job `gh:artipie/rpm-adapter#117` is not assigned, can't get performer

**Comment by 0pdd** [comment]
The puzzle `83-a430163f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#219](https://github.com/artipie/rpm-adapter/issues/219), [#220](https://github.com/artipie/rpm-adapter/issues/220) are still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#117` is not assigned, can't get performer

**Comment by paulodamaso** [comment]
@g4s8 It is stuck, please take a look

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/117#issuecomment-641410870))

@olenagerasimova Job `gh:artipie/rpm-adapter#117` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#254](https://github.com/artipie/rpm-adapter/issues/254), [#255](https://github.com/artipie/rpm-adapter/issues/255) are still not solved; solved: [#219](https://github.com/artipie/rpm-adapter/issues/219), [#220](https://github.com/artipie/rpm-adapter/issues/220).

**Comment by paulodamaso** [comment]
@olenagerasimova please take a look at this one, it seems stuck

**Comment by paulodamaso** [comment]
@olenagerasimova ping

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/117#issuecomment-645824011))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#117](https://github.com/artipie/rpm-adapter/issues/117) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23117%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat pay 30min @paulodamaso

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#255](https://github.com/artipie/rpm-adapter/issues/255), [#366](https://github.com/artipie/rpm-adapter/issues/366) are still not solved; solved: [#219](https://github.com/artipie/rpm-adapter/issues/219), [#220](https://github.com/artipie/rpm-adapter/issues/220), [#254](https://github.com/artipie/rpm-adapter/issues/254).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#219](https://github.com/artipie/rpm-adapter/issues/219), [#220](https://github.com/artipie/rpm-adapter/issues/220), [#254](https://github.com/artipie/rpm-adapter/issues/254), [#255](https://github.com/artipie/rpm-adapter/issues/255), [#366](https://github.com/artipie/rpm-adapter/issues/366).
