### ISSUE TITLE
Download RPM test packages before integration tests

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#120]
Download RPM packages from the file list before running `RpmITCase` (this test is enabled with `longTests` profile) and put it to storage used by `generatesMetadata()` test method instead of resolving built-in resources.

The URL for downloading is: http://mirror.centos.org/centos/7/os/x86_64/Packages/ just add rpm file name to URL, e.g. http://mirror.centos.org/centos/7/os/x86_64/Packages/cups-filters-libs-1.0.35-26.el7.x86_64.rpm

The list of packages to download (1200 packages): [packages.txt](https://github.com/artipie/rpm-adapter/files/4482447/packages.txt)

**Comment by 0crat** [comment]
The job [#120](https://github.com/artipie/rpm-adapter/issues/120) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/abc5ae80-1f02-44b6-bf97-de51c3faed78); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by olenagerasimova** [comment]
@HDouss hm, yesterday this issue was assigned to me and I'm submitting PR...

**Comment by HDouss** [comment]
@olenagerasimova Ok. I will refuse the task

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/120#issuecomment-619225118))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#120](https://github.com/artipie/rpm-adapter/issues/120), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/120#issuecomment-619225118))

@HDouss Job refused in 4 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#120](https://github.com/artipie/rpm-adapter/issues/120) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6b1b2c75-9aee-4616-890d-47a57d215d9e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 please, can you help as here? I've submitted PR for this issue, but 0crat is still assigning this job.

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/120#issuecomment-619392137))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#120](https://github.com/artipie/rpm-adapter/issues/120), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/120#issuecomment-619392137))

@ammaratef45 Job refused in 14 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#120](https://github.com/artipie/rpm-adapter/issues/120) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/50327952-69ae-479e-b707-f070688f7af6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#151](https://github.com/artipie/rpm-adapter/issues/151) is still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 please close issue, #146 was merged

**Comment by g4s8** [comment]
@olenagerasimova thanks

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6d493ca1-e1fd-4f5c-9139-8d69db279e5e, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:artipie/rpm-adapter#120" exists in boosts.xml, but the job is absent in the WBS among 59 jobs.
```

[0.53.13](https://github.com/zerocracy/farm): CID: [3ff1cb7f-fb80-4778-b0dd-aa7896a7821e](https://www.0crat.com/footprint/CT2E6TK9B/3ff1cb7f-fb80-4778-b0dd-aa7896a7821e), Type: "Remove job from WBS"

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#151](https://github.com/artipie/rpm-adapter/issues/151) is solved here.
