### ISSUE TITLE
Add CLI jar to release assets on tag

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#123]
Create new GitHub action to build [CLI RPM tool](https://github.com/artipie/rpm-adapter#cli) on release GitHub event and upload target `target/rpm-adapter.jar` to release assets similar to https://github.com/artipie/white-paper/blob/master/.github/workflows/build-latex.yml#L28

**Comment by 0crat** [comment]
The job [#123](https://github.com/artipie/rpm-adapter/issues/123) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7c4b5dd2-cd56-4c9d-84d1-64449fa62051); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.7.2`

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
