### ISSUE TITLE
Update metadata for changed packages only

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#124]
Currently, RPM `batchUpdate` methods works this way:
 - create new metadata files (`primary.xml`, `filelists.xml` , `others.xml`)
 - download RPM files from storage
 - extract metadata for each RPM
 - update new metadata files with package metadata by appending RPM metadata to the end of XML stream writer
 - close metadata files, update main `repomd.xml` file and replace old metadata files with new

It works very slow for huge repositories (>1000 RPM packages) when only few packages added (or updated/deleted). We need to filter out packages which was not changed and update only fresh packages.

I suppose we can read `primary.xml` metadata files and remember checksusms for each package and update only packages with different checksums and remove packages from metadata files where checksum was not found across new RPM files.

**Comment by 0crat** [comment]
The job [#124](https://github.com/artipie/rpm-adapter/issues/124) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/48356e07-38f5-4253-a3da-4fb3938dc8cf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138) are still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 please close this issue, we are working on puzzles now

**Comment by olenagerasimova** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/124#issuecomment-618933481))

@olenagerasimova This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#124](https://github.com/artipie/rpm-adapter/issues/124) is [in scope](http://www.zerocracy.com/policy.html#14) for 8days
  * The role is `DEV`
  * The job is assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23124%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat out

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#141](https://github.com/artipie/rpm-adapter/issues/141) are still not solved; solved: [#138](https://github.com/artipie/rpm-adapter/issues/138).

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality goood

**Comment by 0crat** [comment]
> @0crat quality goood ([here](https://github.com/artipie/rpm-adapter/issues/124#issuecomment-618946258))

@sereshqua Argument "goood" doesn't match regex `good|bad|acceptable`

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#137](https://github.com/artipie/rpm-adapter/issues/137), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145) are still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#138](https://github.com/artipie/rpm-adapter/issues/138).

**Comment by jeffzhu503** [comment]
What are the performance data for this scenario: "It works very slow for huge repositories (>1000 RPM packages) when only few packages added (or updated/deleted). We need to filter out packages which was not changed and update only fresh packages." ? Shall we publish the data in Github wiki page?

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167) are still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#144](https://github.com/artipie/rpm-adapter/issues/144).

**Comment by g4s8** [comment]
> What are the performance data for this scenario: "It works very slow for huge repositories (>1000 RPM packages) when only few packages added (or updated/deleted). We need to filter out packages which was not changed and update only fresh packages." ? Shall we publish the data in Github wiki page?
> We shall also use one of established project/product to find out what the performance they have. Just for the comparison.

@jeffzhu503 we can compare with `createrepo` native tool for generating RPM metadata on Centos, and generate performance reports on release to attach this report to release assets.

**Comment by jeffzhu503** [comment]
Please come up the list of metrics you want to measure, how would you like to measure.  Do you want to compare these metrics to any existing competitor? If, so please set up the environment for both.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178) are still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#177](https://github.com/artipie/rpm-adapter/issues/177), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167), [#178](https://github.com/artipie/rpm-adapter/issues/178).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#192](https://github.com/artipie/rpm-adapter/issues/192) is still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#224](https://github.com/artipie/rpm-adapter/issues/224) is still not solved; solved: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@g4s8 all 14 puzzles are solved here: [#135](https://github.com/artipie/rpm-adapter/issues/135), [#136](https://github.com/artipie/rpm-adapter/issues/136), [#137](https://github.com/artipie/rpm-adapter/issues/137), [#138](https://github.com/artipie/rpm-adapter/issues/138), [#141](https://github.com/artipie/rpm-adapter/issues/141), [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#145](https://github.com/artipie/rpm-adapter/issues/145), [#167](https://github.com/artipie/rpm-adapter/issues/167), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193), [#224](https://github.com/artipie/rpm-adapter/issues/224).
