### ISSUE TITLE
Cli.java:68-69: Right now Rpm always includes filelists -...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#129]
The puzzle `79-4e9f7178` from #79 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/3e5cdb7f84634189781bc08d9312edc6c695dfdd/src/main/java/com/artipie/rpm/Cli.java#L68-L69

The puzzle was created by @g4s8 on 20-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 53 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [e7326c26-56ec-48b8-baf3-f4f70a824005](https://www.0crat.com/footprint/CT2E6TK9B/e7326c26-56ec-48b8-baf3-f4f70a824005), Type: "Add job to WBS"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 53 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [9e40df0d-14a2-43f8-81fd-076b3b1e0736](https://www.0crat.com/footprint/CT2E6TK9B/9e40df0d-14a2-43f8-81fd-076b3b1e0736), Type: "Add job to WBS"

**Comment by 0crat** [comment]
The job [#129](https://github.com/artipie/rpm-adapter/issues/129) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5c64f0ab-fb53-474e-9709-c608b8ea626d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/129#issuecomment-626087824))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#129](https://github.com/artipie/rpm-adapter/issues/129), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/129#issuecomment-626557605))

@carlosmiranda Job `gh:artipie/rpm-adapter#129` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#129](https://github.com/artipie/rpm-adapter/issues/129) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/184b577b-910f-4f9e-bb37-7148e26ad146); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/129#issuecomment-627246728))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#129](https://github.com/artipie/rpm-adapter/issues/129), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/129#issuecomment-627246728))

@victornoel Job refused in 13 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#129](https://github.com/artipie/rpm-adapter/issues/129) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/36e1de7b-9690-40e1-9dac-7427bce16397); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `79-4e9f7178` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
