### ISSUE TITLE
Change license header 

### ISSUE THREAD

**Issue by Sammers21** [artipie/rpm-adapter#13]
`Yegor Bugayenko` should be changed to `artipie.com`

**Comment by 0crat** [comment]
Job [#13](https://github.com/artipie/rpm-adapter/issues/13) is already in scope

**Comment by 0crat** [comment]
The job [#13](https://github.com/artipie/rpm-adapter/issues/13) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b1d5c5ad-8dbf-4f45-b618-5834196cdccb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@Sammers21 @g4s8 see PR #93

**Comment by carlosmiranda** [comment]
@Sammers21 @g4s8 done in #93. May we close this now?

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 13@fa40d1075ed3, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/rpm-adapter#13" exists in estimates.xml, but the job is absent in the WBS among 43 jobs.
```

[0.53.1](https://github.com/zerocracy/farm): CID: [833af633-049f-4bb0-8e80-d4faf84eccfa](https://www.0crat.com/footprint/CT2E6TK9B/833af633-049f-4bb0-8e80-d4faf84eccfa), Type: "Remove job from WBS"

**Comment by sereshqua** [comment]
@0crat quality good
