### ISSUE TITLE
RpmITCase depends on an inexistent folder

### ISSUE THREAD

**Issue by HDouss** [artipie/rpm-adapter#132]
`RpmITCase` test relies on a classpath folder named "rpms", but the project does not have such a folder.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@HDouss please, can you check this test now? We transformed it do download test bundles. If everything fine, could you please close this issue?

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#132` is not assigned, can't get performer
