### ISSUE TITLE
RpmITCase is not running on Github Actions workflow

### ISSUE THREAD

**Issue by HDouss** [artipie/rpm-adapter#133]
Due to `it.longtests.enabled` system property that should be equal to true for RpmITCase, we should add a system property in the workflow definition file `maven.yml`, so the methods in that test got executed. For now, the build succeeds without running those tests.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by HDouss** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@HDouss let's wait for #120 to be resolved first

**Comment by olenagerasimova** [comment]
@HDouss @g4s8 I think we can close this issue, `RpmITCase` is currently running in integration test action, for example https://github.com/artipie/rpm-adapter/pull/163/checks?check_run_id=655403317

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#133` is not assigned, can't get performer
