### ISSUE TITLE
FilelistsOutput.java:36-38: Modify this class and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#135]
The puzzle `124-5bce57f2` from #124 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/bab36bf10c263f5316c53ac1cb335d4b3289aad2/src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java#L36-L38

The puzzle was created by @g4s8 on 22-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by g4s8** [comment]
@0crat assign @olenagerasimova

**Comment by 0crat** [comment]
> @0crat assign @olenagerasimova  ([here](https://github.com/artipie/rpm-adapter/issues/135#issuecomment-618298868))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.scope.wbs.add_label_to_github_ticket
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [e2db8bc8-7892-4a7e-9e1b-316b985d0cd9](https://www.0crat.com/footprint/CT2E6TK9B/e2db8bc8-7892-4a7e-9e1b-316b985d0cd9), Type: "Job was added to WBS"

**Comment by 0crat** [comment]
> @0crat assign @olenagerasimova  ([here](https://github.com/artipie/rpm-adapter/issues/135#issuecomment-618298868))

@g4s8 The job [#135](https://github.com/artipie/rpm-adapter/issues/135) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9ef6e28c-a503-4605-a345-e24d2255d64e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `124-5bce57f2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 27 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
