### ISSUE TITLE
OthersOutput.java:36-38: Modify this class and XmlOthers...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#136]
The puzzle `124-3102e87b` from #124 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/bab36bf10c263f5316c53ac1cb335d4b3289aad2/src/main/java/com/artipie/rpm/pkg/OthersOutput.java#L36-L38

The puzzle was created by @g4s8 on 22-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by g4s8** [comment]
@0crat assign @olenagerasimova

**Comment by 0crat** [comment]
> @0crat assign @olenagerasimova  ([here](https://github.com/artipie/rpm-adapter/issues/136#issuecomment-618299137))

@g4s8 The job [#136](https://github.com/artipie/rpm-adapter/issues/136) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/43a4cbe1-6f0f-4681-b36c-3c2f72e4d304); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `124-3102e87b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#143](https://github.com/artipie/rpm-adapter/issues/143), [#167](https://github.com/artipie/rpm-adapter/issues/167) are still not solved; solved: [#144](https://github.com/artipie/rpm-adapter/issues/144).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#143](https://github.com/artipie/rpm-adapter/issues/143), [#144](https://github.com/artipie/rpm-adapter/issues/144), [#167](https://github.com/artipie/rpm-adapter/issues/167).
