### ISSUE TITLE
PrimaryOutput.java:36-38: Modify this class and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#138]
The puzzle `124-6b3b1cde` from #124 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/bab36bf10c263f5316c53ac1cb335d4b3289aad2/src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java#L36-L38

The puzzle was created by @g4s8 on 22-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `124-6b3b1cde` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#141](https://github.com/artipie/rpm-adapter/issues/141) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#138` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178) are still not solved; solved: [#141](https://github.com/artipie/rpm-adapter/issues/141).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#177](https://github.com/artipie/rpm-adapter/issues/177), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved; solved: [#141](https://github.com/artipie/rpm-adapter/issues/141), [#178](https://github.com/artipie/rpm-adapter/issues/178).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved; solved: [#141](https://github.com/artipie/rpm-adapter/issues/141), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#192](https://github.com/artipie/rpm-adapter/issues/192) is still not solved; solved: [#141](https://github.com/artipie/rpm-adapter/issues/141), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#224](https://github.com/artipie/rpm-adapter/issues/224) is still not solved; solved: [#141](https://github.com/artipie/rpm-adapter/issues/141), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@0pdd all 6 puzzles are solved here: [#141](https://github.com/artipie/rpm-adapter/issues/141), [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193), [#224](https://github.com/artipie/rpm-adapter/issues/224).
