### ISSUE TITLE
Migrate to asto 0.4

### ISSUE THREAD

**Issue by Sammers21** [artipie/rpm-adapter#14]

**Comment by g4s8** [comment]
@Sammers21 the latest version of asto is `0.13` now: https://github.com/artipie/asto/tree/0.13.2

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by 0crat** [comment]
> @0crat assign @Sammers21  ([here](https://github.com/artipie/rpm-adapter/issues/14#issuecomment-588152855))

@g4s8 The job [#14](https://github.com/artipie/rpm-adapter/issues/14) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/30ac6a50-f892-4289-927e-7d1110573bc4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@Sammers21 fixed in #21

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) everybody who has role `DEV` is banned at [#14](https://github.com/artipie/rpm-adapter/issues/14); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
