### ISSUE TITLE
PrimaryOutput.java:36-37: Make this class be able to work...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#141]
The puzzle `138-e82cce42` from #138 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/1e9e4fb1419e4c21c94ab7ccecedbe4b157297cb/src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java#L36-L37

The puzzle was created by olenagerasimova on 22-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#141](https://github.com/artipie/rpm-adapter/issues/141) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f882b274-e467-43f4-91e6-26d9d6e3186a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `138-e82cce42` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#177](https://github.com/artipie/rpm-adapter/issues/177), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved; solved: [#178](https://github.com/artipie/rpm-adapter/issues/178).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved; solved: [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#192](https://github.com/artipie/rpm-adapter/issues/192) is still not solved; solved: [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#224](https://github.com/artipie/rpm-adapter/issues/224) is still not solved; solved: [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#177](https://github.com/artipie/rpm-adapter/issues/177), [#178](https://github.com/artipie/rpm-adapter/issues/178), [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193), [#224](https://github.com/artipie/rpm-adapter/issues/224).
