### ISSUE TITLE
Run parallel

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#148]
Run metadata parsers for `batchUpdate` in parallel depending on CPU count.

**Comment by 0crat** [comment]
The job [#148](https://github.com/artipie/rpm-adapter/issues/148) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ca2d9be5-7a89-4f30-93e6-797c73ee8291); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.8`

**Comment by g4s8** [comment]
Fixed
