### ISSUE TITLE
DownloadBundle.java:39-40: Create test for this class and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#151]
The puzzle `120-b9c4d61d` from #120 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/fef8ecbb34f39a598e735b91b89096f349810e9a/src/test/java/com/artipie/rpm/files/DownloadBundle.java#L39-L40

The puzzle was created by olenagerasimova on 24-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#151](https://github.com/artipie/rpm-adapter/issues/151) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/10f0472c-e1c1-4950-9666-f24b35053553); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `120-b9c4d61d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
