### ISSUE TITLE
There is something wrong with XmlPackagesFile behaviour

### ISSUE THREAD

**Issue by victornoel** [artipie/rpm-adapter#159]
I am working on #147 and I noticed that `XmlPackagesFile` is counting the number of packages but never write it down at the end.

In the past there was a method called `XmlFile.alterTag` that was responsible of writing down this information but it seems that it was removed.

At the same time, I can see that `ModifiableMetadata` seems to be writing the number of packages into some files.

Also I can see there is now duplication of some information between XmlXXX and XXXOutput: for example `FilelistsOutput` has `tag()` method that returns `"filelists"` while `XmlFilelists` has `new XmlPackagesFile(xml, "filelists", "http://linux.duke.edu/metadata/filelists");`

It looks like to me the responsibilities of those objects are overlapping, it makes thing less maintainable and easy to understand.

For example, I can see that `OthersOutput` uses tag `others` with `XmlOthers` uses `otherdata`, this looks like a potential bug to me...

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#159](https://github.com/artipie/rpm-adapter/issues/159) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/cd07a904-d888-464f-86cc-a903e5ab5331); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@victornoel the puzzle [#194](https://github.com/artipie/rpm-adapter/issues/194) is still not solved.

**Comment by olenagerasimova** [comment]
@victornoel please check #186 and close this issue if possible

**Comment by victornoel** [comment]
@olenagerasimova thx

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@victornoel the only puzzle [#194](https://github.com/artipie/rpm-adapter/issues/194) is solved here.
