### ISSUE TITLE
CI is all broken

### ISSUE THREAD

**Issue by victornoel** [artipie/rpm-adapter#161]
Apparently the CI is all broken, see:
- https://github.com/artipie/rpm-adapter/runs/636089140?check_suite_focus=true
  - there are old puzzles that doesn't pass the checks
- https://github.com/artipie/rpm-adapter/runs/636089098?check_suite_focus=true
  - codecov can't run

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#161](https://github.com/artipie/rpm-adapter/issues/161) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fc54956e-7a82-4771-b182-49cede746898); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@victornoel the puzzle [#168](https://github.com/artipie/rpm-adapter/issues/168) is still not solved.

**Comment by g4s8** [comment]
@victornoel @olenagerasimova I've also renamed check names in #169 and enabled it as required

**Comment by victornoel** [comment]
@g4s8 @olenagerasimova I think I can close this then, thanks :)

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@victornoel the only puzzle [#168](https://github.com/artipie/rpm-adapter/issues/168) is solved here.
