### ISSUE TITLE
Upload API

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#162]
Let's create custom upload API, since RPM specification doesn't have the standard way for uploading.

## Upload HTTP request

Method: `PUT`

URI: `/package.rpm` - the name of RPM package

Query params:
 - `override` (optional) - if `true`, override existing package with same name

Body: RPM package data

## Upload process

User sends RPM package as `PUT` HTTP request with RPM data in body.

RPM adapter `Slice` implementation should process this request, store the package in repository without changing the name.
If package with same name already exist and `override` query param flag is not `true`, then return `409` error.

Artipie `Slice` reutrns `202` status on success and trigger metadata update asynchronously, it should not run multiple metadata updates simultaneously.

**Comment by 0crat** [comment]
The job [#162](https://github.com/artipie/rpm-adapter/issues/162) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8a3a22fb-2bee-4244-bce0-295ee6ab7beb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/162#issuecomment-625670470))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#162](https://github.com/artipie/rpm-adapter/issues/162), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/162#issuecomment-625670470))

@carlosmiranda Job refused in 16 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#162](https://github.com/artipie/rpm-adapter/issues/162) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3f5893cf-980b-471d-bb47-e8bbe007a1e4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/artipie/rpm-adapter/pull/199

**Comment by olenagerasimova** [comment]
@g4s8 why query URI does not have repository key? How we would know in what rpm repo this uploaded rpm should be added and what metadata files to update?

**Comment by g4s8** [comment]
> @g4s8 why query URI does not have repository key? How we would know in what rpm repo this uploaded rpm should be added and what metadata files to update?

@olenagerasimova @paulodamaso I suppose we will trim this path on Artipie level using these classes soon: https://github.com/artipie/http/pull/164 because RPM repository doesn't need such information as repository name: Artipie server finds the relevant RPM repository, RPM repository updates metadata files based on relative path. Does it make sense?

**Comment by olenagerasimova** [comment]
@g4s8 I'm not sure I understand the idea: now we can update/create rpm repositories by `key` - that means that there are several repositories in our storage. If I want to put one more rpm file into one of the existing rpm repository I have to know the repository `key`. Or in this case we will obtain repo key from `X-FullPath` header?

**Comment by g4s8** [comment]
@olenagerasimova repository storage doesn't care about full path of repository in storage, for example the user sends the request to upload: `PUT https://central.artipie.com/centos8/nginx-1.0.rpm`, Artipie routing removes `/centos8` part from the path and `RpmSlice` receives `PUT https://central.artipie.com/nginx-1.0.rpm` request (path = `/nginx-1.0.rpm`), and it's uploading the file to storage by the key `/nginx-1.0.rpm` - Artipie provisions each repository with isolated `Storage` instance, where the root of each storage is pointing to the root of **repository storage space**. So when you're working inside repository, you don't care about storage locations, you may think that each repository has different storage. Actually, it's implemented by prefixing all keys for repository storage with repository name, e.g. each storage operation to `/nginx-1.0.rpm` will be translated to `/centos8/nginx-1.0.rpm` key automatically. See https://github.com/artipie/artipie/blob/8263055c68f8a8524b63d0a75051f9d0a9d68782/src/main/java/com/artipie/RepoConfig.java#L126

**Comment by olenagerasimova** [comment]
@g4s8 thanks for the explanation, I got it now

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#253](https://github.com/artipie/rpm-adapter/issues/253) is still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 please close, #253 was merged

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#162` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#260](https://github.com/artipie/rpm-adapter/issues/260) is still not solved; solved: [#253](https://github.com/artipie/rpm-adapter/issues/253).

**Comment by paulodamaso** [comment]
@g4s8 I didn't got paid for this one, please take a look

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/162#issuecomment-644518703))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#162](https://github.com/artipie/rpm-adapter/issues/162) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23162%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#253](https://github.com/artipie/rpm-adapter/issues/253), [#260](https://github.com/artipie/rpm-adapter/issues/260).

**Comment by g4s8** [comment]
@0crat pay 30min @paulodamaso
