### ISSUE TITLE
XmlAlter.java:45-46: Create separate proper unit-test for...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#167]
The puzzle `144-e68f383c` from #144 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/3dc2e6f2332aab3f52ae239b647020356173e99e/src/main/java/com/artipie/rpm/meta/XmlAlter.java#L45-L46

The puzzle was created by olenagerasimova on 07-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova are you going to fix it by yourself, or we can delegate it to 0crat developers?

**Comment by olenagerasimova** [comment]
@g4s8 I think it would be convenient (or even necessary) to do it together with #164 and so please assign me this issue

**Comment by 0crat** [comment]
The job [#167](https://github.com/artipie/rpm-adapter/issues/167) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/663aa970-0369-4348-bec2-dedc86592cd7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `144-e68f383c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
