### ISSUE TITLE
FileList index feature is necessary

### ISSUE THREAD

**Issue by LuBan-Liu** [artipie/rpm-adapter#17]
1、We should support filelist feature.
2、It is necessary to be able to switch

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@luban-liu[/z](https://www.0crat.com/u/luban-liu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Sammers21** [comment]
@LuBan-Liu, Storage interface has a list method. You can use it

**Comment by LuBan-Liu** [comment]
Next week,i will try it. Thanks you job.

**Comment by Sammers21** [comment]
@LuBan-Liu , can you try to explain your issue more precisely? What do you mean by ` filelist feature`?

**Comment by LuBan-Liu** [comment]
Now. I havan't got the version to resolve the problem.

**Comment by Sammers21** [comment]
@LuBan-Liu , sure, the issues still is not resolved. Can you give us more details?

**Comment by LuBan-Liu** [comment]
let me explain the issues  as precise as you can .as below:
We want to use a param to control the filelist feature.
When the param is ture, we should produce the filelist file.
When the param is false,we don't need to produce the filelist file.

**Comment by Sammers21** [comment]
@LuBan-Liu , How does this feature works in artifactory or createreapo? Does they produce filelist.xml files each time or what?

**Comment by LuBan-Liu** [comment]
There is a switch param which belongs to one rpm repo.When the param is ture,  upload the rpm packege to the rpm repo .we should product the filelist file.  the problem is :  We want to transfer the param to rpm-adapter,How can i do it?

**Comment by Sammers21** [comment]
@LuBan-Liu , it is clear what you need. It is not clear why do you need that. What is wrong with `filelist.xml` generation on each update?

**Comment by g4s8** [comment]
@LuBan-Liu did I get you correctly: we're generating the file `filelists.xml` and updating `repomd.xml` with this `filelists` file. You want to configure `Rpm` in a such way that it won't generate this file. But as I can see in the documentation of `createrepo` https://linux.die.net/man/8/createrepo and in [Artifactory](https://www.jfrog.com/confluence/display/JFROG/RPM+Repositories) documentation, this file is required by [yum](https://linux.die.net/man/8/yum) tool, and we can't omit it because `yum` won't be able to find files to install without this file, so these changes may break default RPM tool.
Can you provide any use case of this feature or scenario how it can be used? It seems if you use this feature your code won't work correctly. Do we really need it?

**Comment by LuBan-Liu** [comment]
As I know, yum install rpm package by primary file. filelists file may be used when we query the rpm information. 
second, jfrog artifactory has the switch which be used to control the filelist file. we only want to Keep in line with commercial artifactory.

**Comment by g4s8** [comment]
@LuBan-Liu it's described by "Indexing the File List " section of Artifactory docs: https://www.jfrog.com/confluence/display/JFROG/RPM+Repositories

**Comment by 0crat** [comment]
Thanks for your contribution, @luban-liu[/z](https://www.0crat.com/u/luban-liu)! If you would be a member of [the project](https://www.0crat.com/p/CT2E6TK9B), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#17](https://github.com/artipie/rpm-adapter/issues/17) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b2348831-0994-431e-ae2f-9b7d660c1a22); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#17](https://github.com/artipie/rpm-adapter/issues/17), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#17](https://github.com/artipie/rpm-adapter/issues/17) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c5e65403-7e8c-4779-87cd-c2144723b6f6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #42 merge

**Comment by g4s8** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/artipie/rpm-adapter/issues/17#issuecomment-607882434))

@g4s8 Boost 4x was set for [#17](https://github.com/artipie/rpm-adapter/issues/17)

**Comment by 0pdd** [comment]
@LuBan-Liu the puzzle [#70](https://github.com/artipie/rpm-adapter/issues/70) is still not solved.

**Comment by paulodamaso** [comment]
@LuBan-Liu PR #42 was merged, please close the issue

**Comment by 0pdd** [comment]
@LuBan-Liu the only puzzle [#70](https://github.com/artipie/rpm-adapter/issues/70) is solved here.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@LuBan-Liu please make sure you start all your comments with the name of the user they are referred to, [see](https://github.com/artipie/rpm-adapter/issues/17#issuecomment-593302268) for instance

**Comment by sereshqua** [comment]
@LuBan-Liu ping

**Comment by paulodamaso** [comment]
@sereshqua ping

**Comment by sereshqua** [comment]
@paulodamaso still waiting for @LuBan-Liu 's response :)

**Comment by paulodamaso** [comment]
@sereshqua Could you give your veredict on my work? This issue is preventing me from receiving other jobs

**Comment by sereshqua** [comment]
@0crat quality acceptable
