### ISSUE TITLE
ModifiableMetadata.java:38-40: Create tests for this...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#177]
The puzzle `141-769c95ee` from #141 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/359b4670b8fb754efe6a0a1b505e11b5215ec140/src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java#L38-L40

The puzzle was created by @olenagerasimova on 12-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by 0crat** [comment]
The job [#177](https://github.com/artipie/rpm-adapter/issues/177) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c021fcf9-a89f-4534-8cc4-13a5bd75fad4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
