### ISSUE TITLE
Rpm.java:233-238: Finish incremental update: we need to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#178]
The puzzle `141-85a28213` from #141 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/359b4670b8fb754efe6a0a1b505e11b5215ec140/src/main/java/com/artipie/rpm/Rpm.java#L233-L238

The puzzle was created by @olenagerasimova on 12-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193) are still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#178` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#192](https://github.com/artipie/rpm-adapter/issues/192) is still not solved; solved: [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#224](https://github.com/artipie/rpm-adapter/issues/224) is still not solved; solved: [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#192](https://github.com/artipie/rpm-adapter/issues/192), [#193](https://github.com/artipie/rpm-adapter/issues/193), [#224](https://github.com/artipie/rpm-adapter/issues/224).
