### ISSUE TITLE
The return value needs to be optimized

### ISSUE THREAD

**Issue by LuBan-Liu** [artipie/rpm-adapter#18]
Once the updata processing is complete, you need to return to the production file stream list. It includes other file stream/ primary file stream /repomd.xml file stream /filelist file stream.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@luban-liu[/z](https://www.0crat.com/u/luban-liu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Sammers21** [comment]
@LuBan-Liu , those files can be obtained from `Stroage`

**Comment by LuBan-Liu** [comment]
Get it. Thanks.

**Comment by Sammers21** [comment]
@LuBan-Liu, can we close this issue as irrelevant?

**Comment by olenagerasimova** [comment]
not valid anymore

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#18` is not assigned, can't get performer
