### ISSUE TITLE
Cleanup old metadata after update

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#182]
Let's remove old metadata files after update

**Comment by 0crat** [comment]
The job [#182](https://github.com/artipie/rpm-adapter/issues/182) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e332049b-0902-47fa-94b1-4d2bec9b1692); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.2`

**Comment by g4s8** [comment]
Fixed in `0.8.2`

**Comment by 0crat** [comment]
Job was finished in 32 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
