### ISSUE TITLE
Update ASTO dep

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#188]
Update asto dependency to `0.20` version

**Comment by 0crat** [comment]
The job [#188](https://github.com/artipie/rpm-adapter/issues/188) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2b792e7c-9c12-41f6-98ef-bf727ae3434a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Done in #189

**Comment by 0crat** [comment]
Job was finished in 31 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
