### ISSUE TITLE
Update interface needs to be redefined

### ISSUE THREAD

**Issue by LuBan-Liu** [artipie/rpm-adapter#19]
We should redefine this interface to support different business scenarios.
For example 

```
class RepoData {
       String filename.
       InputStream fileStream.
}
RepoData repoData updata(RepoData[] repodata,String[] fileList,String model)
```

Description:
1、repodata:Existing repodata data needs to be transferd
2、filelist:Batch files need to generate repodata.
3、model: Add or delete files
4、we hope you can return the file stream.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@luban-liu[/z](https://www.0crat.com/u/luban-liu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by LuBan-Liu** [comment]
@yegor256

**Comment by Sammers21** [comment]
@LuBan-Liu, thank you for reporting this issue.
>We should redefine this interface to support different business scenarios.
For example
class RepoData {
       String filename.
       InputStream fileStream.
}
RepoData repoData updata(RepoData[] repodata,String[] fileList,String model)

Can you please clarify what do you mean by this?

**Comment by Sammers21** [comment]
@LuBan-Liu, keep in mind that the library does not operate with `InputStream` and `OutputStream`s. We use flows from Java 9, they are non blocking and back-pressured

**Comment by LuBan-Liu** [comment]
Good Job. Thanks.

**Comment by Sammers21** [comment]
@LuBan-Liu, so you mean we should close this issues as irrelevant? right?

**Comment by LuBan-Liu** [comment]
No. I think it must be resolved.

**Comment by LuBan-Liu** [comment]
still have a question

**Comment by g4s8** [comment]
> still have a question

@LuBan-Liu what's your question?

**Comment by LuBan-Liu** [comment]
This qustion description is too complicated.  close it and open one more issue. make it a little simple.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#19` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
