### ISSUE TITLE
RpmTest.java:43-45: Don't change metadata when invalid...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#190]
The puzzle `63-70804367` from #63 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/65b9bd9d1257f5e8a19bf12f98f7026613c55429/src/test/java/com/artipie/rpm/RpmTest.java#L43-L45

The puzzle was created by paulodamaso on 01-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `63-70804367` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#218](https://github.com/artipie/rpm-adapter/issues/218) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#190` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#218](https://github.com/artipie/rpm-adapter/issues/218) is solved here.
