### ISSUE TITLE
Rpm.java:333-334: Try to get rid of blocking operations...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#192]
The puzzle `178-1f21b2fa` from #178 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/e5a38985a4382403957c410b34d41f19e60873ce/src/main/java/com/artipie/rpm/Rpm.java#L333-L334

The puzzle was created by @olenagerasimova on 14-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#192](https://github.com/artipie/rpm-adapter/issues/192) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/011ec7a5-d3ba-488d-95b0-7ccd2411488f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `178-1f21b2fa` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#224](https://github.com/artipie/rpm-adapter/issues/224) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#192` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#224](https://github.com/artipie/rpm-adapter/issues/224) is solved here.
