### ISSUE TITLE
Rpm.java:387-389: Create enum with metadata file items...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#193]
The puzzle `178-21b31f88` from #178 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/e5a38985a4382403957c410b34d41f19e60873ce/src/main/java/com/artipie/rpm/Rpm.java#L387-L389

The puzzle was created by @olenagerasimova on 14-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `178-21b31f88` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#193` is not assigned, can't get performer
