### ISSUE TITLE
XmlPackage.java:34-35: Find all usages of metadata files...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#194]
The puzzle `159-8e7ac748` from #159 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/762e9d6cd167f35feb5637f7b2cde50e812a4ec7/src/main/java/com/artipie/rpm/meta/XmlPackage.java#L34-L35

The puzzle was created by @olenagerasimova on 15-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `159-8e7ac748` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#194` is not assigned, can't get performer
