### ISSUE TITLE
Join xmls without xml-stream

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#200]
Let's try to rewrite `XmlMetaJoin` without xml-streams and see if this is going to be work faster.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#201](https://github.com/artipie/rpm-adapter/issues/201) is still not solved.

**Comment by olenagerasimova** [comment]
closing as #196 was merged

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#200` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#201](https://github.com/artipie/rpm-adapter/issues/201) is solved here.
