### ISSUE TITLE
XmlMetaJoin.java:84-85: This method have to be removed or...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#201]
The puzzle `200-d9ed28fb` from #200 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/178058324ea1b84175e8e6a811ecff896f1e3ab1/src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java#L84-L85

The puzzle was created by @olenagerasimova on 25-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#201](https://github.com/artipie/rpm-adapter/issues/201) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/16e62e43-e0a1-452f-b497-af0f69e53dfc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `200-d9ed28fb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#201` is not assigned, can't get performer
