### ISSUE TITLE
Add junit extension to measure tests time

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#203]
As we need to measure time in several tests, I'd suggest to add something like https://github.com/junit-team/junit5/blob/master/documentation/src/test/java/example/timing/TimingExtension.java.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova can we just use `@Timeout(1)` Junit annotation?

**Comment by olenagerasimova** [comment]
@g4s8 why? Do we want to fail our integration `it.longtests.enabled` if they are taking too long?

**Comment by g4s8** [comment]
@olenagerasimova sorry, I misunderstood your ticket. Then I think it's ok to use this extension for Junit

**Comment by olenagerasimova** [comment]
@g4s8 please, assign me

**Comment by 0crat** [comment]
The job [#203](https://github.com/artipie/rpm-adapter/issues/203) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/83052ab7-19f0-4c61-83b5-0047f6a32671); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
done in #209

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by sereshqua** [comment]
@olenagerasimova FYI, if ticket creator = ticket performer, quality would never be good, sorry :)
