### ISSUE TITLE
MetadataFileTest.java:45-53: MetadataFile is saving an...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#206]
The puzzle `106-c1f3bb3a` from #106 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/8955d042625e3d7a3744865881a4de32346422ce/src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java#L45-L53

The puzzle was created by paulodamaso on 13-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by 0crat** [comment]
The job [#206](https://github.com/artipie/rpm-adapter/issues/206) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/eb4436b0-56a7-4d97-a8aa-f946a87c81ce); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#206](https://github.com/artipie/rpm-adapter/issues/206) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/339ff9c8-bada-4154-81be-36670a5f0407); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9d30a78f-24e0-40c0-befb-fcaad42fdb25, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#206] declared for identity constraint of element "agenda".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [d7c6264c-2e8e-4ca6-8601-4b2aca24e5fe](https://www.0crat.com/footprint/CT2E6TK9B/d7c6264c-2e8e-4ca6-8601-4b2aca24e5fe), Type: "Order was given"

**Comment by 0pdd** [comment]
The puzzle `106-c1f3bb3a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
