### ISSUE TITLE
Consider removing NamingPolicy

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#208]
I'd like to consider removing `NamingPolicy` from `Rpm`: now it's possible to create `Rpm` instance with `sha-256` digest and `NamingPolicy` with `sha-1` digest, which does not make any sense to me. Also, now we are calculating hexes for metadata files twice in `MetadataFile#save`, that is inefficient.   
The other option can be to remove digest dependency from `NamingPolicy`: it would either be plain (without hex prefix) or prefixed.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova why it's not possible to create `Rpm` with `SHA256` or `SHA1`? As I know our clients are using `SHA1` file prefixes with `SHA256` checksums in `repomd.xml`. Also, it's like a standard to save rpm metadata files with `SHA256` checksums.

**Comment by olenagerasimova** [comment]
@g4s8 ok, closing it then
