### ISSUE TITLE
Basic auth for RPM repo

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#213]
Add HTTP basic authentication for RPM download slice, see this SO answer for details: https://stackoverflow.com/a/26852734/1723695

**Comment by 0crat** [comment]
The job [#213](https://github.com/artipie/rpm-adapter/issues/213) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0fd59d70-7284-4902-acb9-1bde647881d9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat wait for #240 to be merged.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#259](https://github.com/artipie/rpm-adapter/issues/259) is still not solved.

**Comment by olenagerasimova** [comment]
@g4s8 please close, #240 was merged

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#273](https://github.com/artipie/rpm-adapter/issues/273) is still not solved; solved: [#259](https://github.com/artipie/rpm-adapter/issues/259).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#290](https://github.com/artipie/rpm-adapter/issues/290) is still not solved; solved: [#259](https://github.com/artipie/rpm-adapter/issues/259), [#273](https://github.com/artipie/rpm-adapter/issues/273).

**Comment by 0pdd** [comment]
@g4s8 all 3 puzzles are solved here: [#259](https://github.com/artipie/rpm-adapter/issues/259), [#273](https://github.com/artipie/rpm-adapter/issues/273), [#290](https://github.com/artipie/rpm-adapter/issues/290).
