### ISSUE TITLE
CliArgumentsTest.testWrongArgumentCount is a bad test

### ISSUE THREAD

**Issue by carlosmiranda** [artipie/rpm-adapter#217]
Current code in `CliArgumentsTest`:

```java
    @Test
    void testWrongArgumentCount() {
        try {
            Cli.main(new String[]{});
        } catch (final IllegalArgumentException exception) {
            MatcherAssert.assertThat(
                String.format("Exception occurred: %s", exception.getMessage()),
                "Expected repository path but got: []",
                new IsEqual<>(exception.getMessage())
            );
        }
    }
```

There is a glaring flaw in this test. I presume `main` is supposed to throw an exception. But _if it is not_, the `catch` block will be skipped and the test will pass (since there are no assertions outside `catch`.

Let's use `assertThrows` instead. See [Junit 5 docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#217](https://github.com/artipie/rpm-adapter/issues/217) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1ecc11e2-efac-4cce-b79d-5a566f969d15); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #239 to be merged

**Comment by victornoel** [comment]
@carlosmiranda this has been fixed

**Comment by carlosmiranda** [comment]
@victornoel thanks!

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/217#issuecomment-641397680))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#217](https://github.com/artipie/rpm-adapter/issues/217) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%23217%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
