### ISSUE TITLE
Rpm file prefixes

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#22]
Add optional support of prefixes for rpm files

**Comment by 0crat** [comment]
The job [#22](https://github.com/artipie/rpm-adapter/issues/22) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b4712a4f-8d1d-40e1-8a19-a03cb9233226); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.1`

**Comment by LuBan-Liu** [comment]
I'll test it today

**Comment by g4s8** [comment]
@LuBan-Liu I updated the documentation in this commit: https://github.com/artipie/rpm-adapter/commit/0aa3dc41cab0f9ae9e78d1672619c5ec1dc047a8
please use `new Rpm(storage, new NamingPolicy.Sha1Prefixed())` to add `SHA1` prefixes to metadata files.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#22` is not assigned, can't get performer
