### ISSUE TITLE
XmlPrimary.java:48-54: Fix 'provides' element generation...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#220]
The puzzle `117-c0f32a4a` from #117 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/bf08bf98313d1469f51ffda619340e3ffd704baf/src/main/java/com/artipie/rpm/meta/XmlPrimary.java#L48-L54

The puzzle was created by paulodamaso on 25-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by 0crat** [comment]
The job [#220](https://github.com/artipie/rpm-adapter/issues/220) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/69a4a025-42a0-40f0-b6bd-35f62b820d84); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `117-c0f32a4a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#254](https://github.com/artipie/rpm-adapter/issues/254), [#255](https://github.com/artipie/rpm-adapter/issues/255) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#255](https://github.com/artipie/rpm-adapter/issues/255), [#366](https://github.com/artipie/rpm-adapter/issues/366) are still not solved; solved: [#254](https://github.com/artipie/rpm-adapter/issues/254).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#254](https://github.com/artipie/rpm-adapter/issues/254), [#255](https://github.com/artipie/rpm-adapter/issues/255), [#366](https://github.com/artipie/rpm-adapter/issues/366).
