### ISSUE TITLE
Extract class from `Rpm#meta`

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#226]
Extract class from `com.artipie.rpm.Rpm#meta` and create proper test for it, this code is repeating in the project.

UPD Changed the issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova don't forget that `Rpm` class is currently in use by our clients, and any API changes are not welcome.

**Comment by olenagerasimova** [comment]
@g4s8 thanks for the reminder, I've updated the issue.

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/226#issuecomment-642418504))

@olenagerasimova The job [#226](https://github.com/artipie/rpm-adapter/issues/226) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/80eca882-a13a-435a-ba3d-d15a1e09486c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#257](https://github.com/artipie/rpm-adapter/issues/257) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#257](https://github.com/artipie/rpm-adapter/issues/257) is solved here.
