### ISSUE TITLE
Extend RpmTest

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#227]
Test for `Rpm` have to be extended:
- [x]  in `doesntBrakeMetadataWhenInvalidPackageSent` we have make sure that not only repomd.xml is not changed, but other 3 metadata files: primary, other and filelist. The best way to check it I see is to stash xmls after the first update and compare them against the files after second update with broken package. 
- [x]  we have to make sure that tempdir is cleaned up after the update
- [x]  it's necessary to verify that old (previous) meta xmls are removed (verified by `StorageHasMetadata` matcher)
- [x]  metadata files are stored in the correct location: `repodata` folder relatively to the prefix (verified by `StorageHasMetadata` matcher)
- [x]  update of the same (with no new/deleted rpms) repository for the second time is successful (covered in `updatesDifferentReposSimultaneouslyTwice`)
- [x]  make sure cleanup is called on different errors (`throwsExceptionWhenFullUpdatesDoneSimultaneously` and `skipsInvalidPackageOnUpdate`)

All the check have to made for both `batchUpdate` and `updateBatchIncrementally`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
all done in `RpmTest`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.3`
