### ISSUE TITLE
Invalid RPM on incremental update

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#228]
Incremental update `updateBatchIncrementally` should behave the same as `updateBatch` if repository contains invalid rpm file: ignore such packages. Add corresponding test first and then fix the behavior.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@g4s8 please assign me

**Comment by 0crat** [comment]
The job [#228](https://github.com/artipie/rpm-adapter/issues/228) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d50c5978-441d-415b-bf6a-b0f508b91aba); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#228](https://github.com/artipie/rpm-adapter/issues/228) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/314a3cec-fcad-49ea-bfc7-ed8eda7b9fdd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0cf2aef6-3274-4e83-b020-be89b679901f, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#228] declared for identity constraint of element "agenda".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [72a31887-8119-43ba-9992-422347a12eed](https://www.0crat.com/footprint/CT2E6TK9B/72a31887-8119-43ba-9992-422347a12eed), Type: "Order was given"

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
#229 merged
