### ISSUE TITLE
RpmITCase is not correct

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#232]
`RpmITCase` is not correct: it's creating `repo` temp directory before each test and extracts the content of RPM test bundle into this directory, but the bundle is extracted as children directory to `repo` dir:
```
repo
+ bundle100/
    + packages.rpm
```
But `batchUpdate` is called against `repo/` directory, we should either move all content of `bundle*` to `repo` and delete `bundle*` or run `batchUpdate` for `repo/bundle*` directory as repository root.

**Comment by 0crat** [comment]
The job [#232](https://github.com/artipie/rpm-adapter/issues/232) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/bec59e13-5d9e-46a4-954b-c71169139952); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 fixed in #233. Honestly, I run this test a lot locally, but I have patch which skips loading and unpacking by moving rpms from once downloaded and unpacked `bundle*` to temp, that's way I never noticed this problem(

**Comment by olenagerasimova** [comment]
@g4s8 please close

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#232](https://github.com/artipie/rpm-adapter/issues/232), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d949d877-ee9b-4ca2-8884-b3e8d426e8d1, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#232] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [97b05b2e-7f68-442b-b46c-7ae43d99da7b](https://www.0crat.com/footprint/CT2E6TK9B/97b05b2e-7f68-442b-b46c-7ae43d99da7b), Type: "Order was canceled"

**Comment by sereshqua** [comment]
@0crat quality good
