### ISSUE TITLE
Introduce class with test rpm

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#235]
Introduce class in the test scope with test rpms, class have to:
- hide paths to test rpms
- be able to add these test rpms into supplied storage (one by one)
- add invalid rpm into storage (see `RpmTest.doesntBrakeMetadataWhenInvalidPackageSent`)

Then use this class in all tests that use test rpms. 
Also, it would be useful to add one any rpm into test resources.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/235#issuecomment-641490839))

@olenagerasimova The job [#235](https://github.com/artipie/rpm-adapter/issues/235) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6a4a98cd-219f-4ac0-b52f-7676dc39da54); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#248](https://github.com/artipie/rpm-adapter/issues/248) is still not solved.

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.9`

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#265](https://github.com/artipie/rpm-adapter/issues/265) is still not solved; solved: [#248](https://github.com/artipie/rpm-adapter/issues/248).

**Comment by 0pdd** [comment]
@olenagerasimova all 2 puzzles are solved here: [#248](https://github.com/artipie/rpm-adapter/issues/248), [#265](https://github.com/artipie/rpm-adapter/issues/265).
