### ISSUE TITLE
Incremental update fails on new repo

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#236]
Incremental update does not work on repository without existing metadata. There are two problems:
- the simple one: `Rpm#meta` fails if metadata file was not found
- the hard one: incremental update parses rpms one by one (if parsing is required) when usual update does it simultaneously. Parallelism is invoked on `Rpm` class level. 

As far as I see, solutions can differ depending on our strategy: are we going to keep 2 updates (incremental and simple) or our goal is to leave incremental update only?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@olenagerasimova I think it would be better to keep only incremental update here.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@661823d7-f32c-4fcc-bf9e-6e35e0472a13, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 28' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [74cd5609-15a1-4b19-bd89-fdd97bd7e5cd](https://www.0crat.com/footprint/CT2E6TK9B/74cd5609-15a1-4b19-bd89-fdd97bd7e5cd), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#236` is not assigned, can't get performer
