### ISSUE TITLE
Batch update support for rpm repository

### ISSUE THREAD

**Issue by LuBan-Liu** [artipie/rpm-adapter#24]
Now  rpm-adapter can generate the repodata files for a single rpm package. That's not enough.
We should support directory-level repodata for all the rpm packages in one directory. As createrepo did.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@luban-liu[/z](https://www.0crat.com/u/luban-liu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@LuBan-Liu see #28 PR

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by olenagerasimova** [comment]
This problem is already fixed and released

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#24` is not assigned, can't get performer
