### ISSUE TITLE
Metadata files validation

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#241]
We need an instrument to validate metadata files in tests. Let's create corresponding classes in test scope, we need to check: 
- metadata is valid xml file
- metadata contains given the number of packages
- metadata has info about given packages

After implementation use these instruments in tests classes.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@g4s8 assign me

**Comment by 0crat** [comment]
The job [#241](https://github.com/artipie/rpm-adapter/issues/241) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/99a67798-642b-4ae0-b2a6-7769203151c9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@olenagerasimova 2 puzzles [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278) are still not solved.

**Comment by olenagerasimova** [comment]
#272 merged

**Comment by 0pdd** [comment]
@olenagerasimova 3 puzzles [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285) are still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova 2 puzzles [#277](https://github.com/artipie/rpm-adapter/issues/277), [#285](https://github.com/artipie/rpm-adapter/issues/285) are still not solved; solved: [#278](https://github.com/artipie/rpm-adapter/issues/278).

**Comment by 0pdd** [comment]
@olenagerasimova 2 puzzles [#277](https://github.com/artipie/rpm-adapter/issues/277), [#307](https://github.com/artipie/rpm-adapter/issues/307) are still not solved; solved: [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285).

**Comment by 0pdd** [comment]
@olenagerasimova 3 puzzles [#277](https://github.com/artipie/rpm-adapter/issues/277), [#310](https://github.com/artipie/rpm-adapter/issues/310), [#311](https://github.com/artipie/rpm-adapter/issues/311) are still not solved; solved: [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285), [#307](https://github.com/artipie/rpm-adapter/issues/307).

**Comment by 0pdd** [comment]
@olenagerasimova 2 puzzles [#310](https://github.com/artipie/rpm-adapter/issues/310), [#311](https://github.com/artipie/rpm-adapter/issues/311) are still not solved; solved: [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285), [#307](https://github.com/artipie/rpm-adapter/issues/307).

**Comment by 0pdd** [comment]
@olenagerasimova 3 puzzles [#310](https://github.com/artipie/rpm-adapter/issues/310), [#316](https://github.com/artipie/rpm-adapter/issues/316), [#317](https://github.com/artipie/rpm-adapter/issues/317) are still not solved; solved: [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285), [#307](https://github.com/artipie/rpm-adapter/issues/307), [#311](https://github.com/artipie/rpm-adapter/issues/311).

**Comment by 0pdd** [comment]
@olenagerasimova 3 puzzles [#310](https://github.com/artipie/rpm-adapter/issues/310), [#359](https://github.com/artipie/rpm-adapter/issues/359), [#360](https://github.com/artipie/rpm-adapter/issues/360) are still not solved; solved: [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285), [#307](https://github.com/artipie/rpm-adapter/issues/307), [#311](https://github.com/artipie/rpm-adapter/issues/311), [#316](https://github.com/artipie/rpm-adapter/issues/316), [#317](https://github.com/artipie/rpm-adapter/issues/317).

**Comment by 0pdd** [comment]
@olenagerasimova 2 puzzles [#310](https://github.com/artipie/rpm-adapter/issues/310), [#360](https://github.com/artipie/rpm-adapter/issues/360) are still not solved; solved: [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285), [#307](https://github.com/artipie/rpm-adapter/issues/307), [#311](https://github.com/artipie/rpm-adapter/issues/311), [#316](https://github.com/artipie/rpm-adapter/issues/316), [#317](https://github.com/artipie/rpm-adapter/issues/317), [#359](https://github.com/artipie/rpm-adapter/issues/359).

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#360](https://github.com/artipie/rpm-adapter/issues/360) is still not solved; solved: [#277](https://github.com/artipie/rpm-adapter/issues/277), [#278](https://github.com/artipie/rpm-adapter/issues/278), [#285](https://github.com/artipie/rpm-adapter/issues/285), [#307](https://github.com/artipie/rpm-adapter/issues/307), [#310](https://github.com/artipie/rpm-adapter/issues/310), [#311](https://github.com/artipie/rpm-adapter/issues/311), [#316](https://github.com/artipie/rpm-adapter/issues/316), [#317](https://github.com/artipie/rpm-adapter/issues/317), [#359](https://github.com/artipie/rpm-adapter/issues/359).
