### ISSUE TITLE
StorageLock.java:35-38: Use this class in RPM update to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#244]
The puzzle `230-3a08fd65` from #230 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/c5b426bf46ca004352abdd1fc8ff4aaf62245abf/src/main/java/com/artipie/rpm/misc/StorageLock.java#L35-L38

The puzzle was created by olenagerasimova on 08-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/244#issuecomment-641175483))

@olenagerasimova The job [#244](https://github.com/artipie/rpm-adapter/issues/244) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c97f9000-4563-42cf-b8a6-9f7c1e6745b0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#244](https://github.com/artipie/rpm-adapter/issues/244), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/244#issuecomment-648043435))

@olenagerasimova The job [#244](https://github.com/artipie/rpm-adapter/issues/244) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/63e2ec3c-5655-4889-b6ca-3576b2389343); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@0crat wait

**Comment by 0pdd** [comment]
The puzzle `230-3a08fd65` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4e431cbc-6ba0-45f1-bfcc-d72a28a8ebf7, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#244] declared for identity constraint of element "speed".
```

[0.54.5](https://github.com/zerocracy/farm): CID: [b5de12de-6112-4203-8eab-43e7f3e53a00](https://www.0crat.com/footprint/CT2E6TK9B/b5de12de-6112-4203-8eab-43e7f3e53a00), Type: "Order was finished"
