### ISSUE TITLE
StorageLock.java:39-40: Consider waiting for the lock to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#245]
The puzzle `230-d8ecbde2` from #230 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/c5b426bf46ca004352abdd1fc8ff4aaf62245abf/src/main/java/com/artipie/rpm/misc/StorageLock.java#L39-L40

The puzzle was created by olenagerasimova on 09-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `230-d8ecbde2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#245` is not assigned, can't get performer
