### ISSUE TITLE
TestRpm.java:37-40: Continue test rpms implementation:...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#248]
The puzzle `235-1ed04df5` from #235 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/aa096e0866386ef37e21436b3241138ae929b895/src/test/java/com/artipie/rpm/TestRpm.java#L37-L40

The puzzle was created by @olenagerasimova on 09-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#248](https://github.com/artipie/rpm-adapter/issues/248) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1544e165-1e72-4d41-86ab-4bf4dcd05852); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `235-1ed04df5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#265](https://github.com/artipie/rpm-adapter/issues/265) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#265](https://github.com/artipie/rpm-adapter/issues/265) is solved here.
