### ISSUE TITLE
Rpm.java:306-307: After...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#250]
The puzzle `240-b0f96bd8` from #240 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/61378de4e7ab8caaebe4df78c707da52928e1cea/src/main/java/com/artipie/rpm/Rpm.java#L306-L307

The puzzle was created by @olenagerasimova on 09-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
Job was finished in 9 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
