### ISSUE TITLE
RpmUpload.java:33-50: Finish implementation of RpmUpload...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#253]
The puzzle `162-efa52435` from #162 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/16abd083878c0dbffbadebf27343c7011fc78378/src/main/java/com/artipie/rpm/http/RpmUpload.java#L33-L50

The puzzle was created by paulodamaso on 24-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/253#issuecomment-642457523))

@olenagerasimova The job [#253](https://github.com/artipie/rpm-adapter/issues/253) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b8f3ccb8-7df0-4ef9-85b8-c7cb5d99f6af); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `162-efa52435` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#260](https://github.com/artipie/rpm-adapter/issues/260) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#260](https://github.com/artipie/rpm-adapter/issues/260) is solved here.
