### ISSUE TITLE
XmlPrimary.java:440-442: Provides entry also can have...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#255]
The puzzle `220-dd2fed2e` from #220 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/a1ea5a436ece42ee3dfa2c19406de9a2d97ac022/src/main/java/com/artipie/rpm/meta/XmlPrimary.java#L440-L442

The puzzle was created by @olenagerasimova on 03-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `220-dd2fed2e` has disappeared from the source code, that's why I closed this issue.
