### ISSUE TITLE
RpmSlice.java:42-46: Add integration tests for RpmSlice...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#259]
The puzzle `213-52d0fd27` from #213 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/a3aca1dfc7d96212ee7b66eb210711976a0cca0e/src/main/java/com/artipie/rpm/http/RpmSlice.java#L42-L46

The puzzle was created by Victor Noël on 07-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/259#issuecomment-643904259))

@olenagerasimova The job [#259](https://github.com/artipie/rpm-adapter/issues/259) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1031098d-a28f-49e1-90e4-c3235804ed0c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `213-52d0fd27` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#273](https://github.com/artipie/rpm-adapter/issues/273) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#290](https://github.com/artipie/rpm-adapter/issues/290) is still not solved; solved: [#273](https://github.com/artipie/rpm-adapter/issues/273).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#273](https://github.com/artipie/rpm-adapter/issues/273), [#290](https://github.com/artipie/rpm-adapter/issues/290).
