### ISSUE TITLE
RpmUpload.java:48-53: Finish implementation of RpmUpload...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#260]
The puzzle `253-431eeb6b` from #253 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/13730e8292b7b1d0f64b64f58fae8670429777c4/src/main/java/com/artipie/rpm/http/RpmUpload.java#L48-L53

The puzzle was created by @olenagerasimova on 11-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@olegmoz don't mind to solve this issue?

**Comment by olegmoz** [comment]
@olenagerasimova yes please assign it on me

**Comment by 0crat** [comment]
The job [#260](https://github.com/artipie/rpm-adapter/issues/260) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9ca5f5b0-823e-471e-b138-7ccb1aebcf8f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job [#260](https://github.com/artipie/rpm-adapter/issues/260) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
Job [#260](https://github.com/artipie/rpm-adapter/issues/260) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
