### ISSUE TITLE
Rename method for incremental update

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#263]
Main methtod in `Rpm` is called `batchUpdate`, so I think that `updateBatchIncrementally` should be renamed to `batchUpdateIncrementally`

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/263#issuecomment-644667179))

@olenagerasimova The job [#263](https://github.com/artipie/rpm-adapter/issues/263) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/206c0650-a0f9-405c-9277-162d9e81cf66); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
#264 merged

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.9.1`

**Comment by g4s8** [comment]
@olenagerasimova please try again

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.9.1`

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.9.1`
