### ISSUE TITLE
TestRpm.java:38-41: Add a method `name()` to this...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#265]
The puzzle `248-3857a8d1` from #248 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/47dceda2395c4f814bbceefae9bc01575bbec399/src/test/java/com/artipie/rpm/TestRpm.java#L38-L41

The puzzle was created by Victor Noël on 16-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#265](https://github.com/artipie/rpm-adapter/issues/265) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9918449e-984f-4289-a8c2-c7802b4cccbd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@olenagerasimova what is the meaning of the `name()` method for `Multiple`?

**Comment by victornoel** [comment]
@0crat wait for answer

**Comment by olenagerasimova** [comment]
@victornoel hm, for now I think it's ok just to throw some exception, `UnsupportedOperationException` for example. If later we will need to add other methods to `TestRpm` which are not consistent with `Multiple` implementation, we can separate these abstractions.

**Comment by victornoel** [comment]
@0crat wait for #284 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #284 to be merged ([here](https://github.com/artipie/rpm-adapter/issues/265#issuecomment-647673047))

@victornoel Job [#265](https://github.com/artipie/rpm-adapter/issues/265) is already on hold

**Comment by 0pdd** [comment]
The puzzle `248-3857a8d1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
