### ISSUE TITLE
Upload API: metadata recalculation 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#271]
Let's extend Upload API  by adding optional false by default query parameter to skip metadata recalculation. Parameter name can be `skip_update`.
How it should work: 
- `skip_update` parameter is present and equals `false` or absent - we save rpm to storage and trigger metadata recalculation by calling `Rpm#batchUpdate`
- `skip_update` parameter is present and equals `true` - we save rpm to storage and that's it

Add described logic to `RpmUpload` slice and do not forget about tests.

**Comment by olenagerasimova** [comment]
@g4s8 please, take a look. Any better suggestions for parameter name?

**Comment by g4s8** [comment]
@olenagerasimova sounds correct. But I'd use another name for query param. Since metadata update is enabled by default, it may look more clear to use optional flag `skip_update` to skip it. WDYT?

**Comment by olenagerasimova** [comment]
@g4s8 sounds good, I've updated description

**Comment by olenagerasimova** [comment]
@olegmoz dot'n you mind implementing this on the next week? Seems like we can do it in two PRs...

**Comment by olegmoz** [comment]
@olenagerasimova yes please assign the ticket

**Comment by 0crat** [comment]
The job [#271](https://github.com/artipie/rpm-adapter/issues/271) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/285f5c3e-fee1-4eef-b104-417bc0485de2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@592e6706-44da-4634-a6e2-8ab630bff16f, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 26' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [9dbc209b-f5c2-483e-84e8-262dc208c455](https://www.0crat.com/footprint/CT2E6TK9B/9dbc209b-f5c2-483e-84e8-262dc208c455), Type: "Job milestoned"

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/271#issuecomment-649219621))

@olenagerasimova Job [#271](https://github.com/artipie/rpm-adapter/issues/271) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/271#issuecomment-649219621))

@olenagerasimova Job [#271](https://github.com/artipie/rpm-adapter/issues/271) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by sereshqua** [comment]
@0crat quality good
