### ISSUE TITLE
RpmSlice.java:42-46: Add integration test for rpm...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#273]
The puzzle `259-71347a14` from #259 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/a92d64bb5a3aa2a5e4aea2e3e7c438bf94615d9a/src/main/java/com/artipie/rpm/http/RpmSlice.java#L42-L46

The puzzle was created by @olenagerasimova on 17-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/273#issuecomment-647338697))

@olenagerasimova The job [#273](https://github.com/artipie/rpm-adapter/issues/273) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/472021a6-6ecc-4155-b4d7-45d337804d48); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@592e6706-44da-4634-a6e2-8ab630bff16f, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 26' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [ccbd70e0-cc31-428a-9284-ff4fca0d4a7f](https://www.0crat.com/footprint/CT2E6TK9B/ccbd70e0-cc31-428a-9284-ff4fca0d4a7f), Type: "Job milestoned"

**Comment by 0pdd** [comment]
The puzzle `259-71347a14` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#290](https://github.com/artipie/rpm-adapter/issues/290) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#290](https://github.com/artipie/rpm-adapter/issues/290) is solved here.
