### ISSUE TITLE
PrimaryOutputTest.java:88-90: Introduce class from this...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#278]
The puzzle `241-a350bc6d` from #241 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/790b309d40175b7014e4e58ca197f2e7f0120b52/src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java#L88-L90

The puzzle was created by olenagerasimova on 18-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@0crat in

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#278](https://github.com/artipie/rpm-adapter/issues/278) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/58d732b3-c340-47ce-9e0b-bac58fe23c92); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@olegmoz don't you mind taking this issue? We need to extract class from method and replace code duplication.

**Comment by olegmoz** [comment]
@olenagerasimova yes please, assign me

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) I see that you unassigned this issue; the order is still assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by olenagerasimova** [comment]
@0crat refuse

**Comment by 0crat** [comment]
The job [#278](https://github.com/artipie/rpm-adapter/issues/278) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3f96155b-bacb-4840-9120-8306bc355d98); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@olegmoz please, implement headers obtaining as it's done in `FilePackage.header()` method, test has simplified version

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/278#issuecomment-648040463))

@olenagerasimova The user @olegmoz[/z](https://www.0crat.com/u/olegmoz) resigned from [#278](https://github.com/artipie/rpm-adapter/issues/278), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#278](https://github.com/artipie/rpm-adapter/issues/278) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f8d380b6-52b7-4a46-80b8-2da809bdeb66); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job [#278](https://github.com/artipie/rpm-adapter/issues/278) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@586d9f4c-3ecc-4a70-b164-2390bfcb7afb, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#278] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [3ff6e4e4-f77b-4795-b959-32dc21010688](https://www.0crat.com/footprint/CT2E6TK9B/3ff6e4e4-f77b-4795-b959-32dc21010688), Type: "Order was finished"

**Comment by 0crat** [comment]
Job [#278](https://github.com/artipie/rpm-adapter/issues/278) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c7fc22bc-bc34-4b92-886c-5bb37239a1aa, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 26' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [4eaf8151-e696-4482-92a1-8e7de049c204](https://www.0crat.com/footprint/CT2E6TK9B/4eaf8151-e696-4482-92a1-8e7de049c204), Type: "Job milestoned"
