### ISSUE TITLE
RepoConfig.java:31-37: Create `Simple` implementation of...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#286]
The puzzle `281-4a7508e7` from #281 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/f5f27bf9d925157f6a859c61880d56b1f374657e/src/main/java/com/artipie/rpm/RepoConfig.java#L31-L37

The puzzle was created by olenagerasimova on 22-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#286](https://github.com/artipie/rpm-adapter/issues/286) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8cf5ecc2-27e9-4580-a8a5-59fe69a36166); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@773dc7f8-970d-444a-b02a-c8dba678f128, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 26' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [92e3ee55-5290-49d5-b498-82731efc6592](https://www.0crat.com/footprint/CT2E6TK9B/92e3ee55-5290-49d5-b498-82731efc6592), Type: "Job milestoned"

**Comment by 0pdd** [comment]
The puzzle `281-4a7508e7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
