### ISSUE TITLE
RepoConfig.java:62-70: Implement this class to read...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#287]
The puzzle `281-e86c51c6` from #281 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/f5f27bf9d925157f6a859c61880d56b1f374657e/src/main/java/com/artipie/rpm/RepoConfig.java#L62-L70

The puzzle was created by olenagerasimova on 22-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#287](https://github.com/artipie/rpm-adapter/issues/287) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a0b9a584-df48-4d2d-a45f-cf62a4618a6b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@773dc7f8-970d-444a-b02a-c8dba678f128, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 26' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [27809fa2-3245-41f7-a247-89fa26534d1c](https://www.0crat.com/footprint/CT2E6TK9B/27809fa2-3245-41f7-a247-89fa26534d1c), Type: "Job milestoned"

**Comment by 0pdd** [comment]
The puzzle `281-e86c51c6` has disappeared from the source code, that's why I closed this issue.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.10`

**Comment by olenagerasimova** [comment]
@rultor release, tag=0.10

**Comment by olenagerasimova** [comment]
@g4s8 please, could you take a look? What's wrong with release?

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.10`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.10`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.10`
