### ISSUE TITLE
RpmSliceYumITCase.java:56-58: We need to test that dnf...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#290]
The puzzle `273-e9afba21` from #273 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/745a3da4126352ce85abec5273ada931773ea3f9/src/test/java/com/artipie/rpm/http/RpmSliceYumITCase.java#L56-L58

The puzzle was created by olenagerasimova on 22-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@artemlazarev don't you mind taking this issue?

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0580059e-ceba-491e-980a-2a75bcaf1058, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 27' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [041438e0-f98d-47e2-8a8a-fb977c02092c](https://www.0crat.com/footprint/CT2E6TK9B/041438e0-f98d-47e2-8a8a-fb977c02092c), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#290](https://github.com/artipie/rpm-adapter/issues/290) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1c072ab1-1913-4c9b-b447-fea528cb8d2b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `273-e9afba21` has disappeared from the source code, that's why I closed this issue.
