### ISSUE TITLE
NodeHasPkgCountTest.java:41-42: Test methods for...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#310]
The puzzle `307-d58d9aca` from #307 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/2054c9db6420a9780c6f62209e0b978cf7783d7b/src/test/java/com/artipie/rpm/hm/NodeHasPkgCountTest.java#L41-L42

The puzzle was created by @olenagerasimova on 30-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#310](https://github.com/artipie/rpm-adapter/issues/310) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/be102424-b7de-4fe6-aece-c95a0a36cf73); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse I'm not on windows

**Comment by 0crat** [comment]
> @0crat refuse I'm not on windows ([here](https://github.com/artipie/rpm-adapter/issues/310#issuecomment-653432467))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#310](https://github.com/artipie/rpm-adapter/issues/310), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse I'm not on windows ([here](https://github.com/artipie/rpm-adapter/issues/310#issuecomment-653432467))

@victornoel Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#310](https://github.com/artipie/rpm-adapter/issues/310) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/07738aa4-c1f0-4030-930b-4638f9a60fae); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/310#issuecomment-670526388))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#310](https://github.com/artipie/rpm-adapter/issues/310), please stop working. Reason for job resignation: Order was cancelled

**Comment by baudoliver7** [comment]
@artipie/maintainers could I fix this ?

**Comment by olenagerasimova** [comment]
@baudoliver7 yes, please
