### ISSUE TITLE
ModifiableMetadata: merge and clean only if necessary 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#314]
ModifiableMetadata needs to be able to work if `old` metadata does not exist/is empty and some logic to optimize actions on `metadata.xmls`:
1. Call `XmlMetaJoin.merge()` only if required: there is nothing to merge if `old` does not exists/empty or if new metadata.xml is empty (no packages were added). In the second case we can simply copy data from `old` to new
2. Call `XmlMaid.clean()` only if required: there is nothing to clean if no packages were removed (`final List<String> pkgs` is empty)

To achieve that a) count accepted packages, b) read `packages` attribute from `old` metadata to count rpm packages and set correct `packages` attribute value on `brush()`.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@661823d7-f32c-4fcc-bf9e-6e35e0472a13, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 28' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [d35dff86-9391-44ae-9b7b-5054e873bfdb](https://www.0crat.com/footprint/CT2E6TK9B/d35dff86-9391-44ae-9b7b-5054e873bfdb), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#314](https://github.com/artipie/rpm-adapter/issues/314) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/526874e6-2813-4758-a9c4-a2a5abb0917b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
done in #329

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@0crat out
