### ISSUE TITLE
StorageHasMetadata.java:44-45: Create proper unit test...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#316]
The puzzle `311-652b1692` from #311 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/20bbb408b8d8cdaa84fc5281867ab830f5f708d7/src/test/java/com/artipie/rpm/hm/StorageHasMetadata.java#L44-L45

The puzzle was created by olenagerasimova on 03-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#316](https://github.com/artipie/rpm-adapter/issues/316) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f2136c6b-83ca-4416-b14e-b513bba1f60f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/316#issuecomment-653915553))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#316](https://github.com/artipie/rpm-adapter/issues/316), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#316](https://github.com/artipie/rpm-adapter/issues/316) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/091caffa-e714-4920-84ca-8ab71e1d62bf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@g4s8 I'm having troubles in understanding what's the purpose of this matcher. I need a better description of it so I can write proper tests.

**Comment by paulodamaso** [comment]
@0crat wait for better description

**Comment by olenagerasimova** [comment]
@paulodamaso please see #330

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/316#issuecomment-670526898))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#316](https://github.com/artipie/rpm-adapter/issues/316), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#316` is not assigned, can't get performer
