### ISSUE TITLE
Calc rpm package digest before saving it to tmp

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#318]
Use `ContentDigest` from `asto` to calculate digest of the rpm package before saving it to temp file and save it to temp only if it is not already listed in metadata files and parsing is required for this package.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@661823d7-f32c-4fcc-bf9e-6e35e0472a13, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 28' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [3de8d799-8a63-4ed5-9aab-f5af2b8aeed8](https://www.0crat.com/footprint/CT2E6TK9B/3de8d799-8a63-4ed5-9aab-f5af2b8aeed8), Type: "Job milestoned"

**Comment by olenagerasimova** [comment]
This issue will not be solved, as the suggested approach is not very good: for now `ModifiableRepository` is written in sequential style and works with temp files, not with `Content`. It's necessary to calculate digest of the temp file to add info abour the new rpms and remove records of the removed ones. 
We may come back to this issue when (or if) `ModifiableRepository` will be rewritten in reactive style.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#318` is not assigned, can't get performer
