### ISSUE TITLE
Access test resources via class-loader

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#319]
This repository has a lot of test resources references via path instead of class-loader of current thread context. Fix it and possible replace code duplication by introducing corresponding classes/methods in test scope.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@661823d7-f32c-4fcc-bf9e-6e35e0472a13, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Week 28' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [845fa4cf-5a97-4d47-9c10-e517f1dc247b](https://www.0crat.com/footprint/CT2E6TK9B/845fa4cf-5a97-4d47-9c10-e517f1dc247b), Type: "Job milestoned"

**Comment by 0crat** [comment]
The job [#319](https://github.com/artipie/rpm-adapter/issues/319) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7b1377fd-4bde-4b6b-8c17-e61df4e7f68f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#319](https://github.com/artipie/rpm-adapter/issues/319) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/50d21162-6ad3-401b-a61a-1c5a4d9a8d9f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@740afc52-4253-4b74-b664-43aa471040ba, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#319] declared for identity constraint of element "agenda".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [0fd78371-bdc7-4ea9-abd1-b559fa9a44b3](https://www.0crat.com/footprint/CT2E6TK9B/0fd78371-bdc7-4ea9-abd1-b559fa9a44b3), Type: "Order was given"

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#319](https://github.com/artipie/rpm-adapter/issues/319), since the job is not in scope anymore
