### ISSUE TITLE
RpmTest.java:52-56: Refactor this test. Convert it to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#32]
The puzzle `30-6f533735` from #30 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/516e1a82d8ca028341fa76176abf40c3384e602b/src/test/java/com/artipie/rpm/RpmTest.java#L52-L56

The puzzle was created by @g4s8 on 10-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#32](https://github.com/artipie/rpm-adapter/issues/32) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1160199c-062f-468d-969f-4d1ad71f3ca9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `30-6f533735` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#40](https://github.com/artipie/rpm-adapter/issues/40) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 33 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#40](https://github.com/artipie/rpm-adapter/issues/40) is solved here.
