### ISSUE TITLE
OthersOutput test

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#320]
Create test for `OthersOutput`, see `PrimaryOutputTest` as an example.

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olenagerasimova** [comment]
closed via #338

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#320` is not assigned, can't get performer
