### ISSUE TITLE
Don't wrap XMLStreamException into IOException

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#323]
We have a lot of places where `XMLStreamException` is wrapped into `IOException`, but is does not seem right: `XMLStreamException` is 

> the base exception for unexpected processing errors

and does not have anything to do with I/O operations failure. Let's fix it by maybe introducing another exception for all possible error while working with xml files.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#323` is not assigned, can't get performer
