### ISSUE TITLE
Use Lock with expiration and retries from ASTO

### ISSUE THREAD

**Issue by olegmoz** [artipie/rpm-adapter#340]
Recently `StorageLock` class has been added to ASTO module. It supports lock expiration by timeout, which is useful for automatic release of locks if server came down with lock acquired. There is also `RetryLock` class which may be used to retry obtaining lock which may fail for different reasons (network failures, competing lock acquire operations etc). Using them will be an improvement over distributed locking used in the project

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#340` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@olegmoz thanks

**Comment by olenagerasimova** [comment]
@rultor release, tag=`1.1`
