### ISSUE TITLE
RPM SDK performance issues

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#388]
RPM SDK has multiple performance issues to be resolved:
 - [x] It copies ALL packages of repository to temporary directory, repository may be huge (e.g. > 500 Gb), so it's very expensive operation, we need to get rid of copying of temporary files
 - [x] For optimization, the SDK user can provide only new packages (not all repository) and all `repodata` files, so we can update metadata based on provided packages. We can add `update(Set<Key>)` method to perform batch update only on selected keys
 - [x] Cleanup without providing packages: SDK can provide a method for removing packages based on checksums (to be discussed)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#397](https://github.com/artipie/rpm-adapter/issues/397) is still not solved.

**Comment by g4s8** [comment]
Done, @olenagerasimova thanks
