### ISSUE TITLE
RpmTest.java:54-56: This test class needs refactoring....

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#40]
The puzzle `32-75a1be06` from #32 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/2e738e22f2702d3267e2acd81b9836b2ce5ec5a1/src/test/java/com/artipie/rpm/RpmTest.java#L54-L56

The puzzle was created by HDouss on 12-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#40](https://github.com/artipie/rpm-adapter/issues/40) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/835f9a38-0295-4fd1-a0a4-2c4078797245); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by dgarus** [comment]
@0pdd wait

https://github.com/artipie/rpm-adapter/issues/55

**Comment by 0pdd** [comment]
> @0pdd wait https://github.com/artipie/rpm-adapter/issues/55

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by dgarus** [comment]
@0crat wait
for https://github.com/artipie/rpm-adapter/issues/55

**Comment by 0pdd** [comment]
The puzzle `32-75a1be06` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dgarus[/z](https://www.0crat.com/u/dgarus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
