### ISSUE TITLE
Update all tests to use junit 5

### ISSUE THREAD

**Issue by brastak** [artipie/rpm-adapter#43]
Currently we use junit 4 in several unit tests. Actual runner is junit 5, but these tests use junit 4 and it works together with junit-vintage-engine.
Need to upgrade all tests to junit 5 and remove redundant libraries.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#43` is not assigned, can't get performer
