### ISSUE TITLE
Don't generate xml files if not needed

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#45]
`Rpm` class generates 7 files on `update()`:
 - `repomd.xml`
 - `primary.xml`
 - `primary.xml.gz`
 - `filelists.xml`
 - `filelists.xml.gz`
 - `other.xml`
 - `other.xml.gz`

Most probably `primary.xml`, `filelists.xml` and `other.xml` files are not needed, since `repomd.xml` (the main metadata file) has a links only to `.xml.gz` versions of these files. Check if `createrepo` tool generates `.xml` versions of metadata files and don't upload it to storage in `Repomd` class if not needed.

**Comment by 0crat** [comment]
The job [#45](https://github.com/artipie/rpm-adapter/issues/45) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fb381402-93cf-426e-b448-684091d795a9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by brastak** [comment]
@g4s8 Please, close it
