### ISSUE TITLE
Re-implement docker container start with testcontainers

### ISSUE THREAD

**Issue by brastak** [artipie/rpm-adapter#47]
Now integration test uses ProcessBuilder to execute docker. Testcontainers library provides higher abstraction level. It allows to create simple-in-use and reusable components. Also, it's designed for the unit testing purpose and provides lots of useful containers to create necessary environment for integration tests runs.

We need to rewrite existing code to start docker container with testcontainers library usage

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#47](https://github.com/artipie/rpm-adapter/issues/47) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/57ed5b36-2a24-4f82-9e3f-7d5b85d654df); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
