### ISSUE TITLE
Repomd uses links to src files instead of gzipped

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#49]
Metadata file `repomd.xml` uses wrong links. E.g. if a source file has a name `123abc-filelists.xml` (where `123abc` is a hashsum of the file), and gzipped file has a name `567def-filelists.xml.gz`, then `repomd.xml` will contains a link:
```xml
<data type="filelists">
  <location href="123abc-filelists.xml.gz" />
  <!-- other data -->
</data>
```
So it just appends `.gz` suffix to source file name instead of using correct gzipped file name.

**Comment by brastak** [comment]
@g4s8 I can not reproduce this issue exactly. Our code does not append hashes to the filenames at all. filelists will be uploaded as filelists.xml and the reference will be the same.
But createrepo tool really appends hashes by default. Also createrepo creates sqlite database by default too - do we need to support this right now? All of options above are correct - hashless filenames, sqlite-less repo and the one is used by createrepo by default. Createrepo behavior can be changed with options. Our current level of support: createrepo --simple-md-filenames --no-database. This command generates exactly the same repomd.xml as our code.

**Comment by g4s8** [comment]
@brastak we also support sha1 prefixes, see `new Rpm(sotrage, new NamingPolicy.Sha1Prefixed())`: https://github.com/artipie/rpm-adapter#naming-policy

**Comment by 0crat** [comment]
The job [#49](https://github.com/artipie/rpm-adapter/issues/49) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/afc0f2cb-2409-403f-8973-71d81d75dc5a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by brastak** [comment]
@g4s8 Looks like we support it in wrong way. We have sha1 prefixes, but checksums in the repomd.xml are sha256. createrepo keeps them consistent - you specify checksum algorithm for both prefixes and tags. I will fix it

**Comment by LuBan-Liu** [comment]
It is best to support alternatives。sha1 or sha256.

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`

**Comment by g4s8** [comment]
@brastak it seems to fixed in #51, right? Can I close this bug?

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by brastak** [comment]
@g4s8 Please, close

**Comment by g4s8** [comment]
@brastak thanks
