### ISSUE TITLE
Rpm adapter should skip primary requires items on condisions

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#492]
During the hotfix #491 the duplicates check for metadata requires items was disabled, since it was implemented not correctly: it just ignores all name duplicates required items, but it should check it with some additional conditions:
```c
                    // Skip duplicate files
                    gpointer value;
                    if (g_hash_table_lookup_extended(ap_hashtable, filename, NULL, &value)) {
                        struct ap_value_struct *ap_value = value;
                        if (!g_strcmp0(ap_value->flags, flags) &&
                            !strcmp(ap_value->version, (full_version ? full_version : "")) &&
                            (ap_value->pre == pre))
                        {
                            continue;
                        }
                    }
```
Duplicate should be checked by its name, flags, version to skip it.

Source (createrepo): https://github.com/rpm-software-management/createrepo_c/blob/master/src/parsehdr.c#L393-L403

**Comment by olenagerasimova** [comment]
@g4s8 to implement it correctly, we also need to calculate `pre` tag (prerequisite) value. To do it, can you please help me to understand this expression:
```
if (num_flags & (RPMSENSE_PREREQ |
                                     RPMSENSE_SCRIPT_PRE |
                                     RPMSENSE_SCRIPT_POST))
                    {
                        pre = 1;
                    }
```
https://github.com/rpm-software-management/createrepo_c/blob/b49b8b2586c07d3e84009beba677162b86539f9d/src/parsehdr.c#L386-L391

I cannot understand the meaning of `RPMSENSE_PREREQ`, `RPMSENSE_SCRIPT_PRE` and `RPMSENSE_SCRIPT_POST` and where to get the values from.

**Comment by g4s8** [comment]
> @g4s8 to implement it correctly, we also need to calculate `pre` tag (prerequisite) value. To do it, can you please help me to understand this expression:
> 
> ```
> if (num_flags & (RPMSENSE_PREREQ |
>                                      RPMSENSE_SCRIPT_PRE |
>                                      RPMSENSE_SCRIPT_POST))
>                     {
>                         pre = 1;
>                     }
> ```
> 
> https://github.com/rpm-software-management/createrepo_c/blob/b49b8b2586c07d3e84009beba677162b86539f9d/src/parsehdr.c#L386-L391
> 
> I cannot understand the meaning of `RPMSENSE_PREREQ`, `RPMSENSE_SCRIPT_PRE` and `RPMSENSE_SCRIPT_POST` and where to get the values from.

This `C` expression means that if `num_flags` value has any of bits from `RPMSENSE_PREREQ`, `RPMSENSE_SCRIPT_PRE` and `RPMSENSE_SCRIPT_POST`, then set `pre` value to `1`.

Example:
```
(using bits here)
RPMSENSE_PREREQ := `0000 1001`
RPMSENSE_SCRIPT_PRE := `0001 0000`
RPMSENSE_SCRIPT_POST := `0000 0011`

ALL_FLAGS := RPMSENSE_PREREQ | RPMSENSE_SCRIPT_PRE | RPMSENSE_SCRIPT_POST = 0001 1011

if num_flags = `1111 1111`, then num_flags & ALL_FLAGS = `0001 1011`, pre := 1
if num_flags = `0000 1111`, then num_flags & ALL_FLAGS = `0000 1011`, pre := 1
if num_flags = `0000 0001`, then num_flags & ALL_FLAGS = `0000 0001`, pre := 1
if num_flags = `1110 0000`, then num_flags & ALL_FLAGS = `0000 0000`, pre := 0
```
