### ISSUE TITLE
Implement `lib.so` version comparison

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#494]
We need to implement comparison of `lib.so` dependencies list. These `lib.so` items are often present in `requires` list and `createrepo` only adds the record with the greatest version, for example from the list
```
                <rpm:entry name="libc.so.6()(64bit)"/>
                <rpm:entry name="libc.so.6(GLIBC_2.14)(64bit)"/>
                <rpm:entry name="libc.so.6(GLIBC_2.2.5)(64bit)"/>
                <rpm:entry name="libc.so.6(GLIBC_2.3)(64bit)"/>
                <rpm:entry name="libc.so.6(GLIBC_2.3.4)(64bit)"/>
                <rpm:entry name="libc.so.6(GLIBC_2.4)(64bit)"/>
```
only `libc.so.6(GLIBC_2.4)(64bit)` should be added to the `requires` list. 

Comparison implementation should work exactly as it's done in `createrepo` source https://github.com/rpm-software-management/createrepo_c/blob/b49b8b2586c07d3e84009beba677162b86539f9d/src/parsehdr.c#L82

It would also be convenient if comparison will implement `Comparator` interface.

**Comment by olenagerasimova** [comment]
@g4s8 please, take a look at this issue. Maybe we can delegate it to someone who knows `c`?

**Comment by olenagerasimova** [comment]
@baudoliver7 hi, have you already started to work on this issue? If not, I guess I have time to do it myself...

**Comment by baudoliver7** [comment]
@g4s8 already started :-)

**Comment by baudoliver7** [comment]
> @baudoliver7 hi, have you already started to work on this issue? If not, I guess I have time to do it myself...

Ooops, I mean @olenagerasimova, sorry
