### ISSUE TITLE
Cleanup files on delete

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#50]
We should cleanup removed files on `Rpm.batchUpdate`, e.g. if repository has these files:
```
111.rpm
222.rpm
333.rpm
```
and user called `Rpm.batchUpdate`, these files will be added to metadata files. But if user removes any `222.rpm` file:
```
111.rpm
333.rpm
```
and call `Rpm.batchUpdate`, then all metadata files will contains links to `222.rpm`. We need to remove this file from metadata files too.

**Comment by 0crat** [comment]
The job [#50](https://github.com/artipie/rpm-adapter/issues/50) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/94b07c43-d25d-499f-ac9a-58aeb3cef558); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by brastak** [comment]
@g4s8 Please, close

**Comment by g4s8** [comment]
@brastak thanks
