### ISSUE TITLE
XmlEvent.java:170-174: Analyze condition by which we add...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#512]
The puzzle `501-b9458298` from #501 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/8d6ee1cf89f524ea63237a6a2d5c353e8d3a5e2d/src/main/java/com/artipie/rpm/meta/XmlEvent.java#L170-L174

The puzzle was created by @baudoliver7 on 31-Jan-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olenagerasimova** [comment]
@g4s8 can we delegate this issue to @baudoliver7 ?
