### ISSUE TITLE
Rpm doesn't remove old versions of metadata file

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#52]
When we use some custom naming policy for metadata files (e.g. hash prefixes), then `Rpm` can update these files but doesn't remove old versions, e.g. if we have files:
```
111-filelists.xml.gz
222-others.xml.gz
333-primary.xml.bz
package-one.rpm
repomd.xml
```
and add new package `package-two.rpm`, then `filelists`, `others` and `primary` will be updated and the name of them will change (because of hash based naming policy): `111-filelists -> aaa-filelists`, `222-others -> bbb-others`, `333-primary -> ccc-primary`. `repomd.xml` will have correct links to new files, but old files will present in the storage:
```
111-filelists.xml.gz
222-others.xml.gz
333-primary.xml.bz
aaa-filelists.xml.gz
bbb-others.xml.gz
ccc-primary.xml.bz
package-one.rpm
repomd.xml
```
We need to remove old versions of files after such updates.

**Comment by 0crat** [comment]
The job [#52](https://github.com/artipie/rpm-adapter/issues/52) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d268294d-0849-4f4b-bc39-996d55b8b8c0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by brastak** [comment]
@g4s8 Please, close

**Comment by g4s8** [comment]
@brastak thanks
