### ISSUE TITLE
Mutil-file scenario repodata produced by rpm-adapter is wrong. please fix it.

### ISSUE THREAD

**Issue by LuBan-Liu** [artipie/rpm-adapter#53]
When we save three rpm package information by blockingStorage, then we use the rpm.batchUpdate to  to generate the repodata,the problem happens as below:

1.The rpm-adapter generated three set of filelist/primary/other files, this is ok, but we prefer to get a set of repodata data.
2. the newest set of filelist/other/primary files only contains one package basic information, this point is wrong. 

I have sent the incorrect repodata.rar to kirill， please refer to them.

fix it.  @g4s8   thanks.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by LuBan-Liu** [comment]
Ok

**Comment by g4s8** [comment]
@LuBan-Liu related to #52

**Comment by 0crat** [comment]
The job [#53](https://github.com/artipie/rpm-adapter/issues/53) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/93bb955d-58f7-4569-a8db-43331ab0a4f4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.5`

**Comment by g4s8** [comment]
@rultor release, tag=`0.5.1`

**Comment by g4s8** [comment]
@LuBan-Liu nexus sonatype is down for some reason, it returns `504 Gateway Time-out` when publishing. I'll try to release after some delay.

**Comment by g4s8** [comment]
@rultor release, tag=`0.51.1`

**Comment by brastak** [comment]
@g4s8 Please, close
