### ISSUE TITLE
Update asto

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#59]
Update asto dependency to fix https://github.com/artipie/asto/issues/142 bug

**Comment by g4s8** [comment]
@rultor release, tag=`0.5.4`

**Comment by g4s8** [comment]
Fixed by https://github.com/artipie/rpm-adapter/commit/2f70283cc68779e71172fbb9940a16767bd768a5

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#59` is not assigned, can't get performer
