### ISSUE TITLE
URL in documentation should be changed

### ISSUE THREAD

**Issue by ammaratef45** [artipie/rpm-adapter#62]
The Origin of RPM Content URL should be changed from https://docs.pulpproject.org/plugins/pulp_rpm/tech-reference/rpm.html to https://docs.pulpproject.org/en/2.9/plugins/pulp_rpm/tech-reference/rpm.html

As the first one isn't working

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@ammaratef45 thanks! Fixed by https://github.com/artipie/rpm-adapter/commit/d9845c23e2b88f12e1ce126d81cede0836aea863

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#62` is not assigned, can't get performer
