### ISSUE TITLE
More unit tests

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#63]
Let's add more tests for `Rpm` metadata generators:
 - verify that it can update multiple files one by one
 - verify that the content is correct for all supported digests and `NamingPolicy` implementations
 - verify that it doesn't brake existing metadata in case of invalid package (e.g. generate metadata for first package, then try to generate for broken package)

**Comment by 0crat** [comment]
The job [#63](https://github.com/artipie/rpm-adapter/issues/63) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d08cf712-9a1b-409b-903f-7d24f9716095); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608286217))

@carlosmiranda Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#63](https://github.com/artipie/rpm-adapter/issues/63) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/12d08727-b0a2-43b4-aaf3-6ffff2376d11); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608375201))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#63](https://github.com/artipie/rpm-adapter/issues/63), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608375201))

@ammaratef45 Job refused in 2 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#63](https://github.com/artipie/rpm-adapter/issues/63) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/60929ce8-6a70-4f78-9088-5a274be70bb4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 `Rpm` metadata generator is the class `Repomd`?

**Comment by victornoel** [comment]
@0crat wait for #67 to be merged

**Comment by g4s8** [comment]
@victornoel no, it's `Rpm` class. `Repomd` is responsible only for `repomd.xml` metadata file.

**Comment by victornoel** [comment]
@g4s8 `Repomd` is used nowhere, and `RepoUpdater` seems to be solving the same problem, I don't get what `Repomd` is for then?

**Comment by g4s8** [comment]
@victornoel it looks like we forgot to delete `Repomd` class. It was replaced with `RepoUpdater` by the hotfix when we faced some critical performance issue with Xembly (it parses `xml` document fully in memory, but some documents in RPM repository may be huge enough). So actually, we need unit tests for `Rpm` class to be sure that it can generate metadata correctly, now we have too few asserts in tests about the metadata content.

**Comment by victornoel** [comment]
@g4s8 well, I guess I did refactor `Repomd` yesterday and write a test for `Repomd` for nothing, I will leave this task for someone else then, I don't want to start again the whole process of wrapping my head around `Rpm` and existing `RpmTest`.

@0crat refuse

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608510473); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@victornoel ok, sorry, I forgot to refactor this module after the fix

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608512407))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#63](https://github.com/artipie/rpm-adapter/issues/63), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-608512407))

@victornoel Job refused in 3 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#63](https://github.com/artipie/rpm-adapter/issues/63) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2c19fef1-b325-44ee-8b3a-6a367906da51); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-618930662))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#63](https://github.com/artipie/rpm-adapter/issues/63), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-618930662))

@HDouss Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#63](https://github.com/artipie/rpm-adapter/issues/63) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d78d94af-e09e-41aa-b43b-485bc0586697); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 `RpmITCase` is very confused and doesn't work. We need it working before thinking in improving it

**Comment by g4s8** [comment]
> @g4s8 `RpmITCase` is very confused and doesn't work. We need it working before thinking in improving it

It's working now, see https://github.com/artipie/rpm-adapter/pull/153

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@g4s8 I'm implementing the third case. How can add packages to the repository programatically so I can add a broken package to it?

**Comment by paulodamaso** [comment]
@0crat wait for #158 review

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#190](https://github.com/artipie/rpm-adapter/issues/190) is still not solved.

**Comment by paulodamaso** [comment]
@g4s8 merged, please close

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#63` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-633586975))

@g4s8 Job `gh:artipie/rpm-adapter#63` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/63#issuecomment-633587439))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#63](https://github.com/artipie/rpm-adapter/issues/63) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%2363%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat pay 30min @paulodamaso

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#218](https://github.com/artipie/rpm-adapter/issues/218) is still not solved; solved: [#190](https://github.com/artipie/rpm-adapter/issues/190).

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#190](https://github.com/artipie/rpm-adapter/issues/190), [#218](https://github.com/artipie/rpm-adapter/issues/218).
