### ISSUE TITLE
Remove incorrect usage of doOnSuccess

### ISSUE THREAD

**Issue by victornoel** [artipie/rpm-adapter#65]
I noticed in the code some places where `doOnSuccess` was used, but incorrectly IMHO.

Sometimes the argument passed to `doOnSuccess` returns a `Completable`, but it will never be executed because `doOnSuccess` does nothing with it. Also sometimes it makes more sense to use `map` when the passed lambda use the builder pattern.

In this module, we have that is wrong https://github.com/artipie/rpm-adapter/blob/daba515d1c70ea1e54516f172bf31b13546df39e/src/main/java/com/artipie/rpm/Repomd.java#L154-L162

We also have that should use `map` imho: https://github.com/artipie/rpm-adapter/blob/daba515d1c70ea1e54516f172bf31b13546df39e/src/main/java/com/artipie/rpm/Repomd.java#L237-L240

~There are no other place in this module, but I think it would make sense to fix it also in other modules?~ there are no other module with this problem

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 I think the correct alternative is:
```java
flatMap(o -> aCompletable(o).toSingleDefault(o))
```

**Comment by victornoel** [comment]
@g4s8 also sometimes `map` can directly be used, for example in https://github.com/artipie/rpm-adapter/blob/daba515d1c70ea1e54516f172bf31b13546df39e/src/main/java/com/artipie/rpm/Repomd.java#L238

**Comment by g4s8** [comment]
@victornoel sure, can you put all places to ticket description (from your comments) and I'll add it to scope.

**Comment by victornoel** [comment]
@g4s8 those are the only two in this module, I updated the description, I will check other modules and create corresponding issue.

**Comment by victornoel** [comment]
@g4s8 luckily, those are the only places

**Comment by victornoel** [comment]
@g4s8 actually I think I will do it as part of #63 because it's going to be needed.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#65` is not assigned, can't get performer
