### ISSUE TITLE
WithFilelists.java:34-37: Implement WithFilelists...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#70]
The puzzle `17-f66e78ab` from #17 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/1ed50fc002326f2f35e79e96e03f746b10deccf9/src/main/java/com/artipie/rpm/WithFilelists.java#L34-L37

The puzzle was created by paulodamaso on 24-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `17-f66e78ab` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#70` is not assigned, can't get performer
