### ISSUE TITLE
Why RepoUpdater?

### ISSUE THREAD

**Issue by yegor256** [artipie/rpm-adapter#71]
Can we rename class `RepoUpdater` to something more object-oriented? https://www.yegor256.com/2015/03/09/objects-end-with-er.html

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#71](https://github.com/artipie/rpm-adapter/issues/71) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5ace811b-d637-4f68-bd2e-0e88df9c82b1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@yegor256 it should be fixed now: #74
