### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/rpm-adapter#73]
Examples in readme should be updated as `Rpm` is deprecated in favour to `RpmAbstraction.Base`. 

Also please correct phrase about `Storage` implementation:

> Then, you implement `com.yegor256.rpm.Storage` interface.

`Storage` from `artipie.asto` should be implemented.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#73](https://github.com/artipie/rpm-adapter/issues/73) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d2d2e9f0-c3b4-4342-9337-ba996da453f9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/rpm-adapter/issues/73#issuecomment-644204024))

@olenagerasimova The job [#73](https://github.com/artipie/rpm-adapter/issues/73) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/346113cc-57a4-4010-befd-831ce705517d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by olenagerasimova** [comment]
#266 merged
