### ISSUE TITLE
Rpm.java:67-71: Add option to exclude `filelists.xml`...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#79]
The puzzle `69-a899429c` from #69 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/493153a41dfc9dcae2bb43d8af290adf7d7acf47/src/main/java/com/artipie/rpm/Rpm.java#L67-L71

The puzzle was created by @g4s8 on 08-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#79](https://github.com/artipie/rpm-adapter/issues/79) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/19aa11d3-da8a-4272-b68f-64f1115dc3f6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/79#issuecomment-612409581))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#79](https://github.com/artipie/rpm-adapter/issues/79), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#79](https://github.com/artipie/rpm-adapter/issues/79) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7d2db45c-eab1-4049-ab4c-431d6db012d4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #119.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #119

**Comment by 0crat** [comment]
> @0crat wait for merge of #119  ([here](https://github.com/artipie/rpm-adapter/issues/79#issuecomment-616019862))

@carlosmiranda Job [#79](https://github.com/artipie/rpm-adapter/issues/79) is already on hold

**Comment by 0pdd** [comment]
The puzzle `69-a899429c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#129](https://github.com/artipie/rpm-adapter/issues/129) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/artipie/rpm-adapter/issues/79#issuecomment-616584313))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@ce4a654318ed, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.7](https://github.com/zerocracy/farm): CID: [399dfd90-3d9c-47e3-a54c-6c167de0c8b3](https://www.0crat.com/footprint/CT2E6TK9B/399dfd90-3d9c-47e3-a54c-6c167de0c8b3), Type: "Complete QA review"

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/artipie/rpm-adapter/issues/79#issuecomment-616962076))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 52 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [51ad6b85-abf7-4e5e-bebe-fdcc6f73fc12](https://www.0crat.com/footprint/CT2E6TK9B/51ad6b85-abf7-4e5e-bebe-fdcc6f73fc12), Type: "Complete QA review"

**Comment by g4s8** [comment]
@0crat pay 35min @carlosmiranda

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/79#issuecomment-618282836))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#79](https://github.com/artipie/rpm-adapter/issues/79) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%2379%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#129](https://github.com/artipie/rpm-adapter/issues/129) is solved here.
