### ISSUE TITLE
Rpm is not tested with multiple files

### ISSUE THREAD

**Issue by yegor256** [artipie/rpm-adapter#8]
At the moment all tests work with a single `.rpm` file. We should extend them and see what happens when we have two or more different `.rpm` files.

**Comment by LuBan-Liu** [comment]
Yes.Now only generate repodate file for a single file.

**Comment by LuBan-Liu** [comment]
We should support to generate repodata for multiple files.

**Comment by olenagerasimova** [comment]
@yegor256 @LuBan-Liu closing this issue as it's not valid anymore: we have tests with multiple rpms, please check `RpmITCase` (hundred rpms) and `RpmTest` (two rpms)

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#8` is not assigned, can't get performer
