### ISSUE TITLE
XmlOthers.java:168-170: Refactor XML classes. Each XML...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#81]
The puzzle `69-30c26981` from #69 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/493153a41dfc9dcae2bb43d8af290adf7d7acf47/src/main/java/com/artipie/rpm/meta/XmlOthers.java#L168-L170

The puzzle was created by @g4s8 on 08-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#81](https://github.com/artipie/rpm-adapter/issues/81) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5730d490-ef67-42b6-9706-a28fb63ee1ac); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #97 to be merged

**Comment by 0pdd** [comment]
The puzzle `69-30c26981` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#103](https://github.com/artipie/rpm-adapter/issues/103), [#104](https://github.com/artipie/rpm-adapter/issues/104), [#105](https://github.com/artipie/rpm-adapter/issues/105) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#104](https://github.com/artipie/rpm-adapter/issues/104), [#105](https://github.com/artipie/rpm-adapter/issues/105) are still not solved; solved: [#103](https://github.com/artipie/rpm-adapter/issues/103).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#105](https://github.com/artipie/rpm-adapter/issues/105), [#147](https://github.com/artipie/rpm-adapter/issues/147) are still not solved; solved: [#103](https://github.com/artipie/rpm-adapter/issues/103), [#104](https://github.com/artipie/rpm-adapter/issues/104).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#105](https://github.com/artipie/rpm-adapter/issues/105) is still not solved; solved: [#103](https://github.com/artipie/rpm-adapter/issues/103), [#104](https://github.com/artipie/rpm-adapter/issues/104), [#147](https://github.com/artipie/rpm-adapter/issues/147).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#103](https://github.com/artipie/rpm-adapter/issues/103), [#104](https://github.com/artipie/rpm-adapter/issues/104), [#105](https://github.com/artipie/rpm-adapter/issues/105), [#147](https://github.com/artipie/rpm-adapter/issues/147).
