### ISSUE TITLE
XmlOthers.java:231-233: Implement changelog method. It's...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#82]
The puzzle `69-43c6c36b` from #69 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/493153a41dfc9dcae2bb43d8af290adf7d7acf47/src/main/java/com/artipie/rpm/meta/XmlOthers.java#L231-L233

The puzzle was created by @g4s8 on 08-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#82](https://github.com/artipie/rpm-adapter/issues/82), see [§21](http://www.zerocracy.com/policy.html#21); @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/rpm-adapter/issues/82#issuecomment-613740088))

@ammaratef45 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#82](https://github.com/artipie/rpm-adapter/issues/82) is [in scope](http://www.zerocracy.com/policy.html#14) for 6days
  * The role is `DEV`
  * The job is assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Frpm-adapter%2382%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/82#issuecomment-615406478))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#82](https://github.com/artipie/rpm-adapter/issues/82), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#82](https://github.com/artipie/rpm-adapter/issues/82) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8f785d83-c283-46d2-8837-3f33d4192f9d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/82#issuecomment-619738571))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#82](https://github.com/artipie/rpm-adapter/issues/82), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#82](https://github.com/artipie/rpm-adapter/issues/82) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9fc04645-9203-478a-9fb1-758817f3f40d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by HDouss** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/82#issuecomment-619810001))

@HDouss The user @hdouss[/z](https://www.0crat.com/u/hdouss) resigned from [#82](https://github.com/artipie/rpm-adapter/issues/82), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/82#issuecomment-619810001))

@HDouss Job refused in 1 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#82](https://github.com/artipie/rpm-adapter/issues/82) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e91d8f6a-f8c6-4ea7-8c6e-dc3af0d131e7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/artipie/rpm-adapter/issues/130

**Comment by paulodamaso** [comment]
@0crat wait for #180 merge

**Comment by 0crat** [comment]
> @0crat wait for #180 merge ([here](https://github.com/artipie/rpm-adapter/issues/82#issuecomment-628153245))

@paulodamaso Job [#82](https://github.com/artipie/rpm-adapter/issues/82) is already on hold

**Comment by 0pdd** [comment]
The puzzle `69-43c6c36b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#191](https://github.com/artipie/rpm-adapter/issues/191) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#82](https://github.com/artipie/rpm-adapter/issues/82), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@771b26b8-67e1-41d2-9b59-49db76911c64, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/rpm-adapter#82] declared for identity constraint of element "speed".
```

[0.53.14](https://github.com/zerocracy/farm): CID: [e788d813-b26d-41a1-a1c4-a464ee8713f5](https://www.0crat.com/footprint/CT2E6TK9B/e788d813-b26d-41a1-a1c4-a464ee8713f5), Type: "Order was canceled"

**Comment by sereshqua** [comment]
@0crat quality good
