### ISSUE TITLE
RpmITCase.java:49-52: This test is failing on Windows...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#86]
The puzzle `69-20779ab6` from #69 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/493153a41dfc9dcae2bb43d8af290adf7d7acf47/src/test/java/com/artipie/rpm/RpmITCase.java#L49-L52

The puzzle was created by Kirill on 08-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#86](https://github.com/artipie/rpm-adapter/issues/86) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/02165ec8-0790-47e0-81af-0f95dde5b8d7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@g4s8 see PR #94

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by carlosmiranda** [comment]
@g4s8 I give up on this. First of all, it seems to be strangely environment specific - I couldn't reproduce it locally even though I'm also on Windows. Then I've tried every fix and workaround and hack I can think of and nothing works on any of the Github Windows check builds.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/86#issuecomment-612787108))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#86](https://github.com/artipie/rpm-adapter/issues/86), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#86](https://github.com/artipie/rpm-adapter/issues/86) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7c67d643-dcb0-4cf6-899a-3a70d549f0c7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/86#issuecomment-612924807))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#86](https://github.com/artipie/rpm-adapter/issues/86), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/rpm-adapter/issues/86#issuecomment-612924807))

@ammaratef45 Job refused in 5 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#86](https://github.com/artipie/rpm-adapter/issues/86) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/30580c8e-832a-487e-8339-366d94b7bfc7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #115 to be merged

**Comment by victornoel** [comment]
@carlosmiranda the file wasn't properly closed before the move happened on it. But the ATOMIC thing was also a good idea I believe, so I left it.

**Comment by carlosmiranda** [comment]
@victornoel good job. I did try to put the file input/output streams in try-with-resources too but my solution didn't work for some reason.

**Comment by victornoel** [comment]
@carlosmiranda shame on me, I simply forgot to remove the `DisabledOnOs` annotation, actually the problem is not fixed ^^

**Comment by victornoel** [comment]
@carlosmiranda finally found the solution: closing an xmlwriterstream does not close the underlying stream :|

**Comment by 0pdd** [comment]
The puzzle `69-20779ab6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 38 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
