### ISSUE TITLE
OOM exception on update

### ISSUE THREAD

**Issue by g4s8** [artipie/rpm-adapter#88]
There're possible OOM error on updating with 200 RPM packages for JVM with 4GB heap.

**Comment by 0crat** [comment]
The job [#88](https://github.com/artipie/rpm-adapter/issues/88) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3203fa3d-2caf-4d59-ab6d-1a1ce824ec44); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
Should be fixed

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
