### ISSUE TITLE
Cli.java:83-87: start execution of the command you can...

### ISSUE THREAD

**Issue by 0pdd** [artipie/rpm-adapter#89]
The puzzle `68-3d243175` from #68 has to be resolved: 

https://github.com/artipie/rpm-adapter/blob/16ab0ee456e65b3378f2a9e82840a5a73cf948e4/src/main/java/com/artipie/rpm/Cli.java#L83-L87

The puzzle was created by @ammaratef45 on 09-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#89](https://github.com/artipie/rpm-adapter/issues/89) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/58225798-5023-4cd9-be8b-7500b09bf56e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `68-3d243175` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#113](https://github.com/artipie/rpm-adapter/issues/113), [#114](https://github.com/artipie/rpm-adapter/issues/114) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#113](https://github.com/artipie/rpm-adapter/issues/113), [#176](https://github.com/artipie/rpm-adapter/issues/176) are still not solved; solved: [#114](https://github.com/artipie/rpm-adapter/issues/114).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#176](https://github.com/artipie/rpm-adapter/issues/176), [#205](https://github.com/artipie/rpm-adapter/issues/205) are still not solved; solved: [#113](https://github.com/artipie/rpm-adapter/issues/113), [#114](https://github.com/artipie/rpm-adapter/issues/114).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#176](https://github.com/artipie/rpm-adapter/issues/176) is still not solved; solved: [#113](https://github.com/artipie/rpm-adapter/issues/113), [#114](https://github.com/artipie/rpm-adapter/issues/114), [#205](https://github.com/artipie/rpm-adapter/issues/205).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#113](https://github.com/artipie/rpm-adapter/issues/113), [#114](https://github.com/artipie/rpm-adapter/issues/114), [#176](https://github.com/artipie/rpm-adapter/issues/176), [#205](https://github.com/artipie/rpm-adapter/issues/205).
