### ISSUE TITLE
Remove slf4j-log4j from classpath

### ISSUE THREAD

**Issue by victornoel** [artipie/rpm-adapter#98]
I noticed that rpm-adapter has slf4j-log4j in its test classpath, but it also has sl4f-simple.

Warnings appears during execution of tests:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/victor/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/victor/.m2/repository/org/slf4j/slf4j-log4j12/1.8.0-alpha2/slf4j-log4j12-1.8.0-alpha2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

As we can see, both are detected but only one used.

For simplicity concerns, I think we should just keep slf4j-simple as it is clearly enough for running tests.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, it's fixed in https://github.com/artipie/rpm-adapter/commit/3375dd7b5210a882f70abd4d3f2b3745fd816f00

**Comment by victornoel** [comment]
@g4s8 thx, just for my understanding, why keep slf4j-log4j?

**Comment by 0crat** [comment]
Job `gh:artipie/rpm-adapter#98` is not assigned, can't get performer

**Comment by g4s8** [comment]
@victornoel because it's configured the same way for all other projects (in parent `pom.xml`), so I don't think we need to use different implementation here

**Comment by victornoel** [comment]
@g4s8 ah yes, thx for the explanation
