### ISSUE TITLE
MetadataFile, as a decorator of PackageOutput, should behave on close()

### ISSUE THREAD

**Issue by victornoel** [artipie/rpm-adapter#99]
Apparently `MetadataFile` does it's mean job during the call to `save()` but I believe it would simplify many things to:
- move this behaviour to `close()`
- pass the digest and naming strategy to its constructor

Like this, there will be no need to explicitly call save in `Repository`: the `repomd.xml` file would be updated as soon as the wrapped metadata file is closed.

Next step would then be to move the content of the `save` method of `Repository` to its `close` method too, to homogenise APIs.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#99](https://github.com/artipie/rpm-adapter/issues/99) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/de177591-2e5d-4dcd-bdd8-c43c17cc273b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 ping, we have #105 waiting for this. You can assign me if you want

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/rpm-adapter/issues/99#issuecomment-636798514))

@g4s8 The job [#99](https://github.com/artipie/rpm-adapter/issues/99) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8e9e0951-7f9f-4c9f-b0b1-119b285706c0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/rpm-adapter/issues/99#issuecomment-645227855))

@olenagerasimova GitHub issue is still open, won't close

**Comment by paulodamaso** [comment]
@0crat wait

**Comment by olenagerasimova** [comment]
@paulodamaso @victornoel I'm closing this issue as I'm planning to reorganize `Repository`, `MetadataFile` and other `MetadataFile` abstractions, I do not see them implementing `Closable` after the reorganization. 
@sereshqua please do not report bad quality on this issue as the job was actually done

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
